//! MediaWiki's English language names (code -> name).
//!
//! Generated from `action=query&meta=languageinfo&liprop=name` on en.wikipedia.org,
//! which returns the same table as `mw.language.fetchLanguageNames('en', 'all')`
//! that `Module:Citation/CS1` inverts for `|language=`. Do not edit by hand;
//! regenerate with that API call if MediaWiki adds languages.

/// `code -> English name`.
pub(crate) const LANGUAGE_NAMES: &[(&str, &str)] = &[
    ("aa", "Afar"),
    ("aae", "Arbëresh"),
    ("ab", "Abkhazian"),
    ("abe", "Western Abenaki"),
    ("abq", "Abaza"),
    ("abq-latn", "Abaza"),
    ("abr", "Abron"),
    ("abs", "Ambonese Malay"),
    ("abu", "Abure"),
    ("ace", "Acehnese"),
    ("acf", "Saint Lucian Creole"),
    ("ach", "Acoli"),
    ("acm", "Iraqi Arabic"),
    ("ada", "Adangme"),
    ("adg", "Andegerebinha"),
    ("adj", "Adjukru"),
    ("ady", "Adyghe"),
    ("ady-cyrl", "Adyghe (Cyrillic script)"),
    ("ady-latn", "Adyghe (Latin script)"),
    ("ae", "Avestan"),
    ("aeb", "Tunisian Arabic"),
    ("aeb-arab", "Tunisian Arabic (Arabic script)"),
    ("aeb-latn", "Tunisian Arabic (Latin script)"),
    ("aec", "Saʽidi Arabic"),
    ("aee", "Northeast Pashai"),
    ("aer", "Eastern Arrernte"),
    ("af", "Afrikaans"),
    ("afa", "Afroasiatic languages"),
    ("afh", "Afrihili"),
    ("agq", "Aghem"),
    ("aha", "Ahanta"),
    ("ahr", "Ahirani"),
    ("aig", "Antiguan and Barbudan Creole English"),
    ("aii", "Assyrian Neo-Aramaic"),
    ("ain", "Ainu"),
    ("ajg", "Ajagbe"),
    ("ajp", "South Levantine Arabic"),
    ("ajp-arab", "South Levantine Arabic (Arabic script)"),
    ("ajp-latn", "South Levantine Arabic (Latin script)"),
    ("ak", "Akan"),
    ("akb", "Batak Angkola"),
    ("akk", "Akkadian"),
    ("akk-latn", "Akkadian (Latin script)"),
    ("akk-xsux", "Akkadian (Cuneiform script)"),
    ("akz", "Alabama"),
    ("alc", "Kawésqar"),
    ("ale", "Aleut"),
    ("ale-cyrl", "Aleut (Cyrillic script)"),
    ("alg", "Algonquian languages"),
    ("aln", "Gheg Albanian"),
    ("alq", "Algonquin"),
    ("als", "Alemannic"),
    ("alt", "Southern Altai"),
    ("aly", "Alyawarr"),
    ("am", "Amharic"),
    ("ami", "Amis"),
    ("amx", "Anmatyerre"),
    ("an", "Aragonese"),
    ("ane", "Xârâcùù"),
    ("ang", "Old English"),
    ("ann", "Obolo"),
    ("anp", "Angika"),
    ("apa", "Southern Athabaskan"),
    ("apc", "Levantine Arabic"),
    ("apc-arab", "Levantine Arabic (Arabic script)"),
    ("apc-latn", "Levantine Arabic (Latin script)"),
    ("apw", "Western Apache"),
    ("ar", "Arabic"),
    ("ar-001", "Modern Standard Arabic"),
    ("arc", "Aramaic"),
    ("are", "Western Arrarnta"),
    ("arn", "Mapuche"),
    ("aro", "Araona"),
    ("arp", "Arapaho"),
    ("arq", "Algerian Arabic"),
    ("ars", "Najdi Arabic"),
    ("art", "constructed languages"),
    ("arw", "Arawak"),
    ("ary", "Moroccan Arabic"),
    ("ary-arab", "Moroccan Arabic (Arabic script)"),
    ("ary-latn", "Moroccan Arabic (Latin script)"),
    ("arz", "Egyptian Arabic"),
    ("as", "Assamese"),
    ("asa", "Asu"),
    ("ase", "American Sign Language"),
    ("ast", "Asturian"),
    ("ath", "Athabaskan languages"),
    ("ati", "Attié"),
    ("atj", "Atikamekw"),
    ("atv", "Northern Altai"),
    ("aus", "Australian Aboriginal languages"),
    ("av", "Avaric"),
    ("avi", "Avikam"),
    ("avk", "Kotava"),
    ("awa", "Awadhi"),
    ("axe", "Ayerrerenge"),
    ("axl", "Lower Southern Aranda"),
    ("ay", "Aymara"),
    ("ayh", "Hadhrami Arabic"),
    ("ayz", "Maybrat"),
    ("az", "Azerbaijani"),
    ("az-arab", "Azerbaijani (Arabic script)"),
    ("az-cyrl", "Azerbaijani (Cyrillic script)"),
    ("az-latn", "Azerbaijani (Latin script)"),
    ("azb", "South Azerbaijani"),
    ("azj", "North Azerbaijani"),
    ("ba", "Bashkir"),
    ("bad", "Banda languages"),
    ("bag", "Tuki"),
    ("bai", "Bamileke languages"),
    ("bal", "Baluchi"),
    ("bal-latn", "Baluchi (Latin script)"),
    ("ban", "Balinese"),
    ("ban-bali", "Balinese (Balinese script)"),
    ("bar", "Bavarian"),
    ("bas", "Basaa"),
    ("bat", "Baltic languages"),
    ("bat-smg", "Samogitian"),
    ("bax", "Bamun"),
    ("bbc", "Batak Toba"),
    ("bbc-batk", "Batak Toba (Batak script)"),
    ("bbc-latn", "Batak Toba (Latin script)"),
    ("bbj", "Ghomala"),
    ("bcc", "Southern Balochi"),
    ("bci", "Baoulé"),
    ("bcl", "Central Bikol"),
    ("bdr", "West Coast Bajau"),
    ("be", "Belarusian"),
    ("be-tarask", "Belarusian (Taraškievica orthography)"),
    ("be-x-old", "Belarusian (Taraškievica orthography)"),
    ("bej", "Beja"),
    ("bem", "Bemba"),
    ("ber", "Berber languages"),
    ("bew", "Betawi"),
    ("bez", "Bena"),
    ("bfa", "Bari"),
    ("bfd", "Bafut"),
    ("bfi", "British Sign Language"),
    ("bfq", "Badaga"),
    ("bft", "Balti"),
    ("bft-tibt", "Balti (Tibetan script)"),
    ("bfw", "Bonda"),
    ("bfz", "Mahasu Pahari"),
    ("bfz-deva", "Mahasu Pahari (Devanagari script)"),
    ("bfz-takr", "Mahasu Pahari (Takri script)"),
    ("bg", "Bulgarian"),
    ("bgc", "Haryanvi"),
    ("bgc-arab", "Haryanvi (Arabic script)"),
    ("bgc-deva", "Haryanvi (Devanagari script)"),
    ("bgn", "Western Balochi"),
    ("bgp", "Eastern Balochi"),
    ("bgq", "Bagri"),
    ("bgq-arab", "Bagri (Arabic script)"),
    ("bgq-deva", "Bagri (Devanagari script)"),
    ("bh", "Bhojpuri"),
    ("bha", "Bharia"),
    ("bhd", "Bhadrawahi"),
    ("bhd-deva", "Bhadrawahi (Devanagari script)"),
    ("bhd-takr", "Bhadrawahi (Takri script)"),
    ("bho", "Bhojpuri"),
    ("bi", "Bislama"),
    ("bik", "Bikol"),
    ("bin", "Bini"),
    ("bjn", "Banjar"),
    ("bkc", "Baka"),
    ("bkh", "Bakoko"),
    ("bkm", "Kom"),
    ("bkn", "Bukitan"),
    ("bla", "Siksiká"),
    ("blc", "Nuxalk"),
    ("blk", "Pa'O"),
    ("blo", "Anii"),
    ("blt", "Tai Dam"),
    ("bm", "Bambara"),
    ("bn", "Bangla"),
    ("bn-sylo", "Bangla (Sylheti Nagri script)"),
    ("bnb", "Bookan"),
    ("bnn", "Bunun"),
    ("bnt", "Bantu languages"),
    ("bny", "Bintulu"),
    ("bo", "Tibetan"),
    ("bol", "Bole"),
    ("bom", "Berom"),
    ("bpy", "Bishnupriya"),
    ("bqi", "Bakhtiari"),
    ("bqz", "Mka'a"),
    ("br", "Breton"),
    ("bra", "Braj"),
    ("brh", "Brahui"),
    ("brh-latn", "Brahui (Latin script)"),
    ("brx", "Bodo"),
    ("bs", "Bosnian"),
    ("bse", "Wushi"),
    ("bsk", "Burushaski"),
    ("bss", "Akoose"),
    ("btd", "Batak Dairi"),
    ("bth", "Biatah"),
    ("btk", "Batak languages"),
    ("btm", "Batak Mandailing"),
    ("bto", "Rinconada Bikol"),
    ("bts", "Batak Simalungun"),
    ("btx", "Batak Karo"),
    ("btz", "Batak Alas-Kluet"),
    ("bua", "Buriat"),
    ("bug", "Buginese"),
    ("bug-bugi", "Buginese (Buginese script)"),
    ("bum", "Bulu"),
    ("bvb", "Bube"),
    ("bwr", "Bura-Pabir"),
    ("bxr", "Russia Buriat"),
    ("byn", "Blin"),
    ("byv", "Medumba"),
    ("bzj", "Belize Kriol"),
    ("bzs", "Brazilian Sign Language"),
    ("ca", "Catalan"),
    ("cad", "Caddo"),
    ("cai", "Mesoamerican languages"),
    ("cak", "Kaqchikel"),
    ("cal", "Carolinian"),
    ("car", "Carib"),
    ("cau", "Caucasian languages"),
    ("cay", "Cayuga"),
    ("cbk", "Chavacano"),
    ("cbk-zam", "Chavacano"),
    ("cch", "Atsam"),
    ("ccp", "Chakma"),
    ("ccp-beng", "Chakma (Bengali script)"),
    ("cdo", "Mindong"),
    ("cdo-hani", "Mindong (Han script)"),
    ("cdo-hant", "Mindong (Traditional Han script)"),
    ("cdo-latn", "Mindong (Latin script)"),
    ("cdz-beng", "Koda (Bengali script)"),
    ("ce", "Chechen"),
    ("ceb", "Cebuano"),
    ("cel", "Celtic languages"),
    ("cgg", "Chiga"),
    ("ch", "Chamorro"),
    ("chb", "Chibcha"),
    ("chg", "Chagatai"),
    ("chk", "Chuukese"),
    ("chm", "Mari"),
    ("chn", "Chinook Jargon"),
    ("cho", "Choctaw"),
    ("chp", "Chipewyan"),
    ("chr", "Cherokee"),
    ("chy", "Cheyenne"),
    ("cic", "Chickasaw"),
    ("ciw", "Chippewa"),
    ("cja", "Western Cham"),
    ("cja-arab", "Western Cham (Arabic script)"),
    ("cja-cham", "Western Cham (Cham script)"),
    ("cja-latn", "Western Cham (Latin script)"),
    ("cjm", "Eastern Cham"),
    ("cjm-arab", "Eastern Cham (Arabic script)"),
    ("cjm-cham", "Eastern Cham (Cham script)"),
    ("cjm-latn", "Eastern Cham (Latin script)"),
    ("cjy", "Jin"),
    ("cjy-hans", "Jin (Simplified Han script)"),
    ("cjy-hant", "Jin (Traditional Han script)"),
    ("ckb", "Central Kurdish"),
    ("ckb-arab", "Central Kurdish (Arabic script)"),
    ("ckb-latn", "Central Kurdish (Latin script)"),
    ("cko", "Anufo"),
    ("ckt", "Chukchi"),
    ("ckv", "Kavalan"),
    ("clc", "Chilcotin"),
    ("cmc", "Chamic languages"),
    ("cmg", "Classical Mongolian"),
    (
        "cmn-latn-cn-pinyin",
        "Mandarin (Latin script, China, Hanyu Pinyin)",
    ),
    (
        "cmn-latn-tw-pinyin",
        "Mandarin (Latin script, Taiwan, Hanyu Pinyin)",
    ),
    (
        "cmn-latn-tw-tongyong",
        "Mandarin (Latin script, Taiwan, Tongyong Pinyin)",
    ),
    (
        "cmn-latn-tw-wadegile",
        "Mandarin (Latin script, Taiwan, Wade-Giles romanization)",
    ),
    ("cnh", "Hakha-Chin"),
    ("cnr", "Montenegrin"),
    ("cnr-cyrl", "Montenegrin (Cyrillic script)"),
    ("cnr-latn", "Montenegrin (Latin script)"),
    ("cnx", "Middle Cornish"),
    ("co", "Corsican"),
    ("coa", "Cocos Malay"),
    ("cop", "Coptic"),
    ("cpe", "English-based creole languages"),
    ("cpf", "French-based creole languages"),
    ("cpp", "Portuguese-based creole languages"),
    ("cps", "Capiznon"),
    ("cpx", "Puxian"),
    ("cpx-hans", "Puxian (Simplified Han script)"),
    ("cpx-hant", "Puxian (Traditional Han script)"),
    ("cpx-latn", "Puxian (Latin script)"),
    ("cr", "Cree"),
    ("cr-cans", "Cree (Canadian Aboriginal syllabics)"),
    ("cr-latn", "Cree (Latin script)"),
    ("crb", "Island Carib"),
    ("crg", "Michif"),
    ("crh", "Crimean Tatar"),
    ("crh-cyrl", "Crimean Tatar (Cyrillic script)"),
    ("crh-latn", "Crimean Tatar (Latin script)"),
    ("crh-ro", "Dobrujan Tatar"),
    ("crj", "Southern East Cree"),
    ("crk", "Plains Cree"),
    ("crl", "Northern East Cree"),
    ("crm", "Moose Cree"),
    ("crp", "creoles and pidgins"),
    ("crr", "Carolina Algonquian"),
    ("crs", "Seselwa Creole French"),
    ("cs", "Czech"),
    ("csb", "Kashubian"),
    ("csw", "Swampy Cree"),
    ("ctg", "Chittagonian"),
    ("cu", "Church Slavic"),
    ("cus", "Cushitic languages"),
    ("cv", "Chuvash"),
    ("cy", "Welsh"),
    ("da", "Danish"),
    ("dag", "Dagbani"),
    ("dak", "Dakota"),
    ("dar", "Dargwa"),
    ("dav", "Taita"),
    ("day", "Land Dayak languages"),
    ("dbj", "Idaʼan"),
    ("ddn", "Dendi"),
    ("de", "German"),
    ("de-1901", "German (traditional orthography)"),
    ("de-at", "Austrian German"),
    ("de-ch", "Swiss High German"),
    ("de-formal", "German (formal address)"),
    ("del", "Delaware"),
    ("den", "Slave"),
    ("dga", "Southern Dagaare"),
    ("dgr", "Dogrib"),
    ("din", "Dinka"),
    ("diq", "Dimli"),
    ("dje", "Zarma"),
    ("djk", "Ndyuka"),
    ("dkr", "Kuijau"),
    ("dlg", "Dolgan"),
    ("dmg", "Upper Kinabatangan"),
    ("dmv", "Dumpas"),
    ("doi", "Dogri"),
    ("doi-arab", "Dogri (Arabic script)"),
    ("doi-deva", "Dogri (Devanagari script)"),
    ("doi-dogr", "Dogri (Dogra script)"),
    ("dpp", "Papar"),
    ("dra", "Dravidian languages"),
    ("drg", "Rungus"),
    ("dro", "Daro-Matu"),
    ("dru", "Rukai"),
    ("dsb", "Lower Sorbian"),
    ("dso", "Desiya"),
    ("dtb", "Eastern Kadazan"),
    ("dtp", "Central Dusun"),
    ("dtr", "Lotud"),
    ("dty", "Doteli"),
    ("dua", "Duala"),
    ("duf", "Dumbea"),
    ("dum", "Middle Dutch"),
    ("dv", "Divehi"),
    ("dyo", "Jola-Fonyi"),
    ("dyu", "Dyula"),
    ("dz", "Dzongkha"),
    ("dzg", "Dazaga"),
    ("ebu", "Embu"),
    ("ee", "Ewe"),
    ("efi", "Efik"),
    ("egl", "Emiliano-Romagnolo"),
    ("egy", "Ancient Egyptian"),
    ("eka", "Ekajuk"),
    ("ekp", "Ekpeye"),
    ("el", "Greek"),
    ("el-cy", "Cypriot Greek"),
    ("elm", "Eleme"),
    ("elx", "Elamite"),
    ("eme", "Emerillon"),
    ("eml", "Emiliano-Romagnolo"),
    ("en", "English"),
    ("en-au", "Australian English"),
    ("en-ca", "Canadian English"),
    ("en-dsrt", "English (Deseret script)"),
    ("en-emodeng", "Early Modern English"),
    ("en-gb", "British English"),
    ("en-in", "Indian English"),
    ("en-jm", "Jamaican English"),
    ("en-nz", "New Zealand English"),
    ("en-shaw", "English (Shavian script)"),
    ("en-simple", "Simple English"),
    ("en-uk", "British English"),
    ("en-us", "American English"),
    ("enm", "Middle English"),
    ("eo", "Esperanto"),
    ("eo-hsistemo", "Esperanto (h-system orthography)"),
    ("eo-shaw", "Esperanto (Shavian script)"),
    ("eo-xsistemo", "Esperanto (x-system orthography)"),
    ("es", "Spanish"),
    ("es-419", "Latin American Spanish"),
    ("es-es", "European Spanish"),
    ("es-formal", "Spanish (formal address)"),
    ("es-mx", "Mexican Spanish"),
    ("es-ni", "Spanish (Nicaragua)"),
    ("ess", "Central Siberian Yupik"),
    ("esu", "Central Yupik"),
    ("et", "Estonian"),
    ("eto", "Eton"),
    ("ett", "Etruscan"),
    ("etu", "Ejagham"),
    ("eu", "Basque"),
    ("ewo", "Ewondo"),
    ("ext", "Extremaduran"),
    ("eya", "Eyak"),
    ("fa", "Persian"),
    ("fa-034", "Persian (South Asia)"),
    ("fa-af", "Dari"),
    ("fab", "Annobonese Creole"),
    ("fan", "Fang"),
    ("fat", "Fanti"),
    ("fax", "Fala"),
    ("fay", "Kuhmareyi"),
    ("ff", "Fula"),
    ("fi", "Finnish"),
    ("fil", "Filipino"),
    ("fit", "Tornedalen Finnish"),
    ("fiu", "Finno-Ugric languages"),
    ("fiu-vro", "Võro"),
    ("fj", "Fijian"),
    ("fkv", "Kvensk"),
    ("fmp", "Fe'Fe'"),
    ("fo", "Faroese"),
    ("fon", "Fon"),
    ("fos", "Siraya"),
    ("fr", "French"),
    ("fr-be", "Belgian French"),
    ("fr-ca", "Canadian French"),
    ("fr-ch", "Swiss French"),
    ("frc", "Cajun French"),
    ("frk", "Frankish"),
    ("frm", "Middle French"),
    ("fro", "Old French"),
    ("frp", "Arpitan"),
    ("frr", "Northern Frisian"),
    ("frs", "Eastern Frisian Low Saxon"),
    ("fsl", "French Sign Language"),
    ("fud", "Futunan"),
    ("fuf", "Pular"),
    ("fur", "Friulian"),
    ("fvr", "Fur"),
    ("fy", "Western Frisian"),
    ("ga", "Irish"),
    ("gaa", "Ga"),
    ("gag", "Gagauz"),
    ("gah", "Alekano"),
    ("gan", "Gan"),
    ("gan-hans", "Gan (Simplified Han script)"),
    ("gan-hant", "Gan (Traditional Han script)"),
    ("gay", "Gayo"),
    ("gba", "Gbaya"),
    ("gbb", "Kaytetye"),
    ("gbk", "Gaddi"),
    ("gbk-deva", "Gaddi (Devanagari script)"),
    ("gbk-takr", "Gaddi (Takri script)"),
    ("gbm", "Garhwali"),
    ("gbz", "Zoroastrian Dari"),
    ("gcf", "Guadeloupean Creole"),
    ("gcr", "Guianan Creole"),
    ("gd", "Scottish Gaelic"),
    ("gdo", "Godoberi"),
    ("gem", "Germanic languages"),
    ("gez", "Geez"),
    ("gil", "Gilbertese"),
    ("gju", "Gujari"),
    ("gju-arab", "Gujari (Arabic script)"),
    ("gju-deva", "Gujari (Devanagari script)"),
    ("gl", "Galician"),
    ("gld", "Nanai"),
    ("glh", "Northwest Pashai"),
    ("glk", "Gilaki"),
    ("gmh", "Middle High German"),
    ("gml", "Middle Low German"),
    ("gmy", "Mycenaean Greek"),
    ("gn", "Guarani"),
    ("gnq", "Ganaʼ"),
    ("goh", "Old High German"),
    ("gom", "Goan Konkani"),
    ("gom-deva", "Goan Konkani (Devanagari script)"),
    ("gom-latn", "Goan Konkani (Latin script)"),
    ("gon", "Gondi"),
    ("gor", "Gorontalo"),
    ("got", "Gothic"),
    ("gpe", "Ghanaian Pidgin"),
    ("grb", "Grebo"),
    ("grc", "Ancient Greek"),
    ("gsg", "German Sign Language"),
    ("gsw", "Alemannic"),
    ("gsw-fr", "Alsatian"),
    ("gu", "Gujarati"),
    ("guc", "Wayuu"),
    ("gum", "Guambiano"),
    ("gur", "Frafra"),
    ("guw", "Gun"),
    ("guz", "Gusii"),
    ("gv", "Manx"),
    ("gwi", "Gwichʼin"),
    ("gya", "Gbaya"),
    ("ha", "Hausa"),
    ("ha-arab", "Hausa (Arabic script)"),
    ("ha-latn", "Hausa (Latin script)"),
    ("ha-ne", "Hausa (Niger)"),
    ("hac", "Gurani"),
    ("hai", "Haida"),
    ("hak", "Hakka Chinese"),
    ("hak-hans", "Hakka (Simplified Han script)"),
    ("hak-hant", "Hakka (Traditional Han script)"),
    ("hak-latn", "Hakka (Latin script)"),
    ("hav", "Havu"),
    ("haw", "Hawaiian"),
    ("hax", "Southern Haida"),
    ("haz", "Hazaragi"),
    ("hbo", "Biblical Hebrew"),
    ("he", "Hebrew"),
    ("hea", "Northern Qiandong Miao"),
    ("hi", "Hindi"),
    ("hi-kthi", "Hindi (Kaithi script)"),
    ("hi-latn", "Hindi (Latin)"),
    ("hif", "Fiji Hindi"),
    ("hif-deva", "Fiji Hindi (Devanagari script)"),
    ("hif-latn", "Fiji Hindi (Latin script)"),
    ("hil", "Hiligaynon"),
    ("him", "Western Pahari"),
    ("hit", "Hittite"),
    ("hit-latn", "Hittite (Latin script)"),
    ("hit-xsux", "Hittite (Cuneiform script)"),
    ("hke", "Hunde"),
    ("hmn", "Hmong"),
    ("hne", "Chhattisgarhi"),
    ("hnj", "Hmong Njua"),
    ("hno", "Northern Hindko"),
    ("ho", "Hiri Motu"),
    ("hoc", "Ho"),
    ("hoc-latn", "Ho (Latin script)"),
    ("hr", "Croatian"),
    ("hr-glag", "Croatian (Glagolitic script)"),
    ("hrx", "Hunsrik"),
    ("hsb", "Upper Sorbian"),
    ("hsn", "Xiang"),
    ("hsn-hans", "Xiang (Simplified Han script)"),
    ("hsn-hant", "Xiang (Traditional Han script)"),
    ("ht", "Haitian Creole"),
    ("hts", "Hadza"),
    ("hu", "Hungarian"),
    ("hu-formal", "Hungarian (formal address)"),
    ("hup", "Hupa"),
    ("hur", "Halkomelem"),
    ("hy", "Armenian"),
    ("hyw", "Western Armenian"),
    ("hz", "Herero"),
    ("ia", "Interlingua"),
    ("iba", "Iban"),
    ("ibb", "Ibibio"),
    ("id", "Indonesian"),
    ("ie", "Interlingue"),
    ("ifu", "Mayoyao Ifugao"),
    ("ig", "Igbo"),
    ("igb", "Ebira"),
    ("igl", "Igala"),
    ("ii", "Sichuan Yi"),
    ("ijo", "Ijaw languages"),
    ("ik", "Inupiaq"),
    ("ike-cans", "Eastern Canadian (Aboriginal syllabics)"),
    ("ike-latn", "Eastern Canadian (Latin script)"),
    ("ikt", "Western Canadian Inuktitut"),
    ("ilo", "Iloko"),
    ("inc", "Indo-Aryan languages"),
    ("ine", "Indo-European languages"),
    ("inh", "Ingush"),
    ("io", "Ido"),
    ("ira", "Iranian languages"),
    ("iro", "Iroquoian languages"),
    ("is", "Icelandic"),
    ("ish", "Esan"),
    ("isk-arab", "Ishkashimi (Arabic script)"),
    ("isk-cyrl", "Ishkashimi (Cyrillic script)"),
    ("isk-latn", "Ishkashimi (Latin script)"),
    ("ist", "Istriot"),
    ("isu", "Isu"),
    ("isv", "Interslavic"),
    ("isv-cyrl", "Interslavic (Cyrillic script)"),
    ("isv-latn", "Interslavic (Latin script)"),
    ("it", "Italian"),
    ("iu", "Inuktitut"),
    ("ivb", "Ibatan"),
    ("izh", "Ingrian"),
    ("izr", "Izere"),
    ("ja", "Japanese"),
    ("ja-hani", "Japanese (Kanji script)"),
    ("ja-hira", "Japanese (Hiragana script)"),
    ("ja-hrkt", "Japanese (Kana script)"),
    ("ja-kana", "Japanese (Katakana script)"),
    ("jac", "Popti'"),
    ("jak", "Jakun"),
    ("jam", "Jamaican Creole English"),
    ("jax", "Jambi Malay"),
    ("jbo", "Lojban"),
    ("jdt", "Judeo-Tat"),
    ("jdt-cyrl", "Judeo-Tat (Cyrillic script)"),
    ("jgo", "Ngomba"),
    ("jje", "Jeju"),
    ("jmc", "Machame"),
    ("jpr", "Judeo-Persian"),
    ("jrb", "Judeo-Arabic"),
    ("juk", "Wapan"),
    ("jut", "Jutish"),
    ("jv", "Javanese"),
    ("jv-java", "Javanese (Javanese script)"),
    ("ka", "Georgian"),
    ("kaa", "Kara-Kalpak"),
    ("kab", "Kabyle"),
    ("kac", "Kachin"),
    ("kag", "Kajaman"),
    ("kai", "Karekare"),
    ("kaj", "Jju"),
    ("kam", "Kamba"),
    ("kar", "Karenic languages"),
    ("kaw", "Kawi"),
    ("kbd", "Kabardian"),
    ("kbd-cyrl", "Kabardian (Cyrillic script)"),
    ("kbd-latn", "Kabardian (Latin script)"),
    ("kbl", "Kanembu"),
    ("kbp", "Kabiye"),
    ("kcg", "Tyap"),
    ("kck", "Kalanga"),
    ("kde", "Makonde"),
    ("kea", "Cape Verdean Creole"),
    ("kek", "Qʼeqchiʼ"),
    ("ken", "Kenyang"),
    ("ker", "Kera"),
    ("kfo", "Koro"),
    ("kfr", "Kutchi"),
    ("kg", "Kongo"),
    ("kge", "Komering"),
    ("kge-arab", "Komering (Arabic script)"),
    ("kgg", "Kusunda"),
    ("kgp", "Kaingang"),
    ("kha", "Khasi"),
    ("khi", "Khoisan languages"),
    ("kho", "Khotanese"),
    ("khq", "Koyra Chiini"),
    ("khw", "Khowar"),
    ("ki", "Kikuyu"),
    ("kip", "Sheshi Kham"),
    ("kiu", "Kirmanjki"),
    ("kix", "Khiamniungan Naga"),
    ("kj", "Kuanyama"),
    ("kjh", "Khakas"),
    ("kjp", "Eastern Pwo"),
    ("kk", "Kazakh"),
    ("kk-arab", "Kazakh (Arabic script)"),
    ("kk-cn", "Kazakh (China)"),
    ("kk-cyrl", "Kazakh (Cyrillic script)"),
    ("kk-kz", "Kazakh (Kazakhstan)"),
    ("kk-latn", "Kazakh (Latin script)"),
    ("kk-tr", "Kazakh (Turkey)"),
    ("kkj", "Kako"),
    ("kl", "Kalaallisut"),
    ("kld", "Gamilaraay"),
    ("kln", "Kalenjin"),
    ("kls", "Kalasha"),
    ("kls-arab", "Kalasha (Arabic script)"),
    ("kls-latn", "Kalasha (Latin script)"),
    ("km", "Khmer"),
    ("kmb", "Kimbundu"),
    ("kmr", "Northern Kurdish"),
    ("kmr-arab", "Northern Kurdish (Arabic script)"),
    ("kmr-latn", "Northern Kurdish (Latin script)"),
    ("kmz", "Khorasani Turkic"),
    ("kn", "Kannada"),
    ("knc", "Central Kanuri"),
    ("kne", "Kankanaey"),
    ("knn", "Maharashtrian Konkani"),
    ("knq", "Kintaq"),
    ("ko", "Korean"),
    ("ko-cn", "Korean (China)"),
    ("ko-hani", "Korean (Hanja script)"),
    ("ko-kore", "Korean (mixed script)"),
    ("ko-kp", "Korean (North Korea)"),
    ("ko-kr", "Korean (South Korea)"),
    ("koi", "Komi-Permyak"),
    ("kok", "Konkani"),
    ("kos", "Kosraean"),
    ("koy", "Koyukon"),
    ("kpe", "Kpelle"),
    ("kqr", "Kimaragang"),
    ("kqt", "Klias River Kadazan"),
    ("kqv", "Okolod"),
    ("kr", "Kanuri"),
    ("krc", "Karachay-Balkar"),
    ("kri", "Krio"),
    ("krj", "Kinaray-a"),
    ("krl", "Karelian"),
    ("kro", "Kru languages"),
    ("kru", "Kurukh"),
    ("ks", "Kashmiri"),
    ("ks-arab", "Kashmiri (Arabic script)"),
    ("ks-deva", "Kashmiri (Devanagari script)"),
    ("ksb", "Shambala"),
    ("ksf", "Bafia"),
    ("ksh", "Colognian"),
    ("ksw", "S'gaw Karen"),
    ("ksy-beng", "Kharia Thar (Bengali script)"),
    ("ku", "Kurdish"),
    ("ku-arab", "Kurdish (Arabic script)"),
    ("ku-latn", "Kurdish (Latin script)"),
    ("kum", "Kumyk"),
    ("kus", "Kusaal"),
    ("kut", "Kutenai"),
    ("kv", "Komi"),
    ("kve", "Kalabakan"),
    ("kw", "Cornish"),
    ("kwk", "Kwakʼwala"),
    ("kxd", "Brunei Malay"),
    ("kxi", "Keningau Murut"),
    ("kxn", "Kanowit"),
    ("kxv", "Kuvi"),
    ("ky", "Kyrgyz"),
    ("kyw-beng", "Kurmali (Bengali script)"),
    ("kyw-deva", "Kurmali (Devanagari script)"),
    ("la", "Latin"),
    ("lad", "Ladino"),
    ("lad-hebr", "Ladino (Hebrew script)"),
    ("lad-latn", "Ladino (Latin script)"),
    ("lag", "Langi"),
    ("lah", "Western Panjabi"),
    ("laj", "Lango"),
    ("lam", "Lamba"),
    ("lb", "Luxembourgish"),
    ("lbe", "Lak"),
    ("lcm", "Tungag"),
    ("ldn", "Láadan"),
    ("lem", "Nomaande"),
    ("lez", "Lezghian"),
    ("lfn", "Lingua Franca Nova"),
    ("lg", "Ganda"),
    ("li", "Limburgish"),
    ("li-be", "Belgian Limburgish"),
    ("li-nl", "Dutch Limburgish"),
    ("lij", "Ligurian"),
    ("lij-mc", "Monégasque"),
    ("lil", "Lillooet"),
    ("liv", "Livonian"),
    ("ljp", "Lampung Api"),
    ("lki", "Laki"),
    ("lkt", "Lakota"),
    ("lld", "Ladin"),
    ("lmn", "Lambadi"),
    ("lmn-deva", "Lambadi (Devanagari script)"),
    ("lmn-knda", "Lambadi (Kannada script)"),
    ("lmn-taml", "Lambadi (Tamil script)"),
    ("lmn-telu", "Lambadi (Telugu script)"),
    ("lmo", "Lombard"),
    ("ln", "Lingala"),
    ("lns", "Lamnso'"),
    ("lo", "Lao"),
    ("lol", "Mongo"),
    ("lom", "Loma"),
    ("lou", "Louisiana Creole"),
    ("loz", "Lozi"),
    ("lrc", "Northern Luri"),
    ("lsm", "Saamia"),
    ("lt", "Lithuanian"),
    ("ltg", "Latgalian"),
    ("lu", "Luba-Katanga"),
    ("lua", "Luba-Lulua"),
    ("lud", "Ludic"),
    ("lui", "Luiseno"),
    ("lun", "Lunda"),
    ("luo", "Luo"),
    ("lus", "Mizo"),
    ("lut", "Lushootseed"),
    ("luy", "Luyia"),
    ("luz", "Southern Luri"),
    ("lv", "Latvian"),
    ("lzh", "Literary Chinese"),
    ("lzz", "Laz"),
    ("mad", "Madurese"),
    ("maf", "Mafa"),
    ("mag", "Magahi"),
    ("mai", "Maithili"),
    ("mak", "Makasar"),
    ("mak-bugi", "Makasar (Buginese script)"),
    ("man", "Mandingo"),
    ("map", "Austronesian languages"),
    ("map-bms", "Banyumasan"),
    ("mas", "Masai"),
    ("maw", "Mampruli"),
    ("mcn", "Massa"),
    ("mcp", "Maka"),
    ("mde", "Maba"),
    ("mdf", "Moksha"),
    ("mdh", "Maguindanaon"),
    ("mdr", "Mandar"),
    ("men", "Mende"),
    ("mer", "Meru"),
    ("mey", "Hassaniyya"),
    ("mfa", "Kelantan-Pattani Malay"),
    ("mfe", "Morisyen"),
    ("mg", "Malagasy"),
    ("mga", "Middle Irish"),
    ("mgh", "Makhuwa-Meetto"),
    ("mgo", "Metaʼ"),
    ("mh", "Marshallese"),
    ("mhk", "Mungaka"),
    ("mhn", "Mòcheno"),
    ("mhr", "Eastern Mari"),
    ("mi", "Māori"),
    ("mic", "Mi'kmaw"),
    ("mid", "Mandaic"),
    ("min", "Minangkabau"),
    ("miq", "Miskito"),
    ("mis", "unsupported language"),
    ("mix", "Mixtec"),
    ("mjd", "Northwestern Maidu"),
    ("mjx-beng", "Mahali (Bengali script)"),
    ("mk", "Macedonian"),
    ("mkh", "Mon-Khmer"),
    ("ml", "Malayalam"),
    ("mn", "Mongolian"),
    ("mn-cyrl", "Mongolian (Cyrillic script)"),
    ("mn-mong", "Mongolian (Mongolian script)"),
    ("mnc", "Manchu"),
    ("mnc-latn", "Manchu (Latin script)"),
    ("mnc-mong", "Manchu (Mongolian script)"),
    ("mni", "Manipuri"),
    ("mni-beng", "Manipuri (Bengali script)"),
    ("mnj", "Munji"),
    ("mno", "Manobo languages"),
    ("mnq", "Minriq"),
    ("mns", "Mansi"),
    ("mnw", "Mon"),
    ("mo", "Moldovan"),
    ("moe", "Innu-aimun"),
    ("moh", "Mohawk"),
    ("mos", "Mossi"),
    ("mr", "Marathi"),
    ("mr-modi", "Marathi (Modi script)"),
    ("mrh", "Mara"),
    ("mrj", "Western Mari"),
    ("mrt", "Marghi Central"),
    ("mrv", "Mangareva"),
    ("ms", "Malay"),
    ("ms-arab", "Malay (Jawi script)"),
    ("msi", "Sabah Malay"),
    ("mt", "Maltese"),
    ("mua", "Mundang"),
    ("mui", "Musi"),
    ("mul", "multiple languages"),
    ("mun", "Munda languages"),
    ("mus", "Muscogee"),
    ("mvf", "Peripheral Mongolian"),
    ("mvi", "Miyako"),
    ("mvi-hira", "Miyako (Hiragana script)"),
    ("mvv", "Tagol"),
    ("mwl", "Mirandese"),
    ("mwr", "Marwari"),
    ("mwv", "Mentawai"),
    ("mww", "Hmong Daw"),
    ("mww-latn", "Hmong Daw (Latin script)"),
    ("my", "Burmese"),
    ("mye", "Myene"),
    ("myn", "Mayan languages"),
    ("myv", "Erzya"),
    ("mzn", "Mazanderani"),
    ("na", "Nauru"),
    ("nah", "Nahuatl"),
    ("nai", "Indigenous languages of North America"),
    ("nan", "Minnan"),
    ("nan-hani", "Minnan (Han script)"),
    ("nan-hans", "Minnan (Simplified Han script)"),
    ("nan-hant", "Minnan (Traditional Han script)"),
    ("nan-latn-pehoeji", "Minnan (Pe̍h-ōe-jī)"),
    ("nan-latn-tailo", "Minnan (Tâi-lô)"),
    ("nap", "Neapolitan"),
    ("naq", "Nama"),
    ("nb", "Norwegian Bokmål"),
    ("nd", "North Ndebele"),
    ("nds", "Low German"),
    ("nds-nl", "Low Saxon"),
    ("ne", "Nepali"),
    ("new", "Newari"),
    ("ng", "Ndonga"),
    ("nge", "Ngémba"),
    ("nia", "Nias"),
    ("nic", "Niger–Congo languages"),
    ("nit", "Southeastern Kolami"),
    ("niu", "Niuean"),
    ("njo", "Ao Naga"),
    ("nl", "Dutch"),
    ("nl-aw", "Aruban Dutch"),
    ("nl-be", "Belgian Dutch"),
    ("nl-cw", "Curaçaoan Dutch"),
    ("nl-informal", "Dutch (informal address)"),
    ("nl-nl", "Netherlands Dutch"),
    ("nl-sr", "Surinamese Dutch"),
    ("nl-sx", "Sint Maarten Dutch"),
    ("nl-u-sd-bebru", "Brussels Dutch"),
    ("nla", "Ngombala"),
    ("nmg", "Kwasio"),
    ("nmz", "Nawdm"),
    ("nn", "Norwegian Nynorsk"),
    ("nn-hognorsk", "Norwegian Høgnorsk"),
    ("nnh", "Ngiemboon"),
    ("nnz", "Nda'Nda'"),
    ("no", "Norwegian"),
    ("nod", "Northern Thai"),
    ("nod-thai", "Northern Thai (Thai script)"),
    ("nog", "Nogai"),
    ("non", "Old Norse"),
    ("non-runr", "Old Norse (Runic script)"),
    ("nov", "Novial"),
    ("nqo", "N’Ko"),
    ("nr", "South Ndebele"),
    ("nrf-gg", "Guernésiais"),
    ("nrf-je", "Jèrriais"),
    ("nrm", "Norman"),
    ("nsk", "Naskapi"),
    ("nsl", "Norwegian Sign Language"),
    ("nso", "Northern Sotho"),
    ("ntd", "Sesayap Tidung"),
    ("nub", "Nubian languages"),
    ("nup", "Nupe"),
    ("nus", "Nuer"),
    ("nv", "Navajo"),
    ("nwc", "Classical Newari"),
    ("nxm", "Numidian"),
    ("ny", "Nyanja"),
    ("nym", "Nyamwezi"),
    ("nyn", "Nyankole"),
    ("nyo", "Nyoro"),
    ("nys", "Nyungar"),
    ("nzi", "Nzima"),
    ("obt", "Old Breton"),
    ("oc", "Occitan"),
    ("oco", "Old Cornish"),
    ("odt", "Old Dutch"),
    ("ofs", "Old Frisian"),
    ("oj", "Ojibwa"),
    ("ojb", "Northwestern Ojibwa"),
    ("ojc", "Central Ojibwa"),
    ("ojp", "Old Japanese"),
    ("ojp-hani", "Old Japanese (Kanji script)"),
    ("ojp-hira", "Old Japanese (Hiragana script)"),
    ("ojs", "Oji-Cree"),
    ("ojw", "Western Ojibwa"),
    ("oka", "Okanagan"),
    ("olo", "Livvi-Karelian"),
    ("om", "Oromo"),
    ("oma", "Omaha-Ponca"),
    ("onw", "Old Nubian"),
    ("ood", "O'odham"),
    ("or", "Odia"),
    ("os", "Ossetic"),
    ("osa", "Osage"),
    ("osa-latn", "Osage (Latin script)"),
    ("osi", "Osing"),
    ("osx", "Old Saxon"),
    ("ota", "Ottoman Turkish"),
    ("otk", "Old Turkish"),
    ("oto", "Otomian languages"),
    ("ovd", "Elfdalian"),
    ("owl", "Old Welsh"),
    ("oym", "Wayampi"),
    ("pa", "Punjabi"),
    ("pa-guru", "Punjabi (Gurmukhi script)"),
    ("paa", "Papuan languages"),
    ("pag", "Pangasinan"),
    ("pal", "Pahlavi"),
    ("pal-phli", "Pahlavi (Inscriptional Pahlavi script)"),
    ("pal-phlp", "Pahlavi (Psalter Pahlavi script)"),
    ("pal-phlv", "Pahlavi (Book Pahlavi script)"),
    ("pam", "Pampanga"),
    ("pao", "Northern Paiute"),
    ("pap", "Papiamento"),
    ("pap-aw", "Papiamento (Aruba)"),
    ("paq", "Parya"),
    ("pau", "Palauan"),
    ("pbb", "Páez"),
    ("pcd", "Picard"),
    ("pcd-be", "Belgian Picard"),
    ("pcd-fr", "French Picard"),
    ("pcm", "Nigerian Pidgin"),
    ("pdc", "Pennsylvania German"),
    ("pdt", "Plautdietsch"),
    ("peo", "Old Persian"),
    ("pfl", "Palatine German"),
    ("pgd", "Gāndhārī"),
    ("pgd-arab", "Gāndhārī (Arabic script)"),
    ("pgd-deva", "Gāndhārī (Devanagari script)"),
    ("pgd-khar", "Gāndhārī (Kharoshthi script)"),
    ("pgl", "Primitive Irish"),
    ("phi", "Philippine languages"),
    ("phl", "Palula"),
    ("phn", "Phoenician"),
    ("phn-latn", "Phoenician (Latin script)"),
    ("phn-phnx", "Phoenician (Phoenician script)"),
    ("phr", "Pahari-Potwari"),
    ("pi", "Pali"),
    ("pi-sidd", "Pali (Siddham script)"),
    ("pih", "Pitcairn-Norfolk"),
    ("pis", "Pijin"),
    ("pjt", "Pitjantjatjara"),
    ("pkc", "Paekche"),
    ("pko", "Pökoot"),
    ("pks", "Pakistan Sign Language"),
    ("pl", "Polish"),
    ("plu", "Palikur"),
    ("plv", "Southwest Palawano"),
    ("plw", "Brooke's Point Palawano"),
    ("pms", "Piedmontese"),
    ("pnb", "Western Punjabi"),
    ("pnt", "Pontic"),
    ("pon", "Pohnpeian"),
    ("pov", "Upper Guinea Crioulo"),
    ("ppl", "Nawat"),
    ("ppu", "Papora-Hoanya"),
    ("pqm", "Maliseet-Passamaquoddy"),
    ("pra", "Prakrit"),
    ("prc", "Parachi"),
    ("prg", "Prussian"),
    ("pro", "Old Provençal"),
    ("prs", "Dari"),
    ("ps", "Pashto"),
    ("ps-af", "Pashto (Afghanistan)"),
    ("ps-pk", "Pashto (Pakistan)"),
    ("psh", "Southwest Pashai"),
    ("psi", "Southeast Pashai"),
    ("psu", "Sauraseni Prākrit"),
    ("psu-arab", "Sauraseni Prākrit (Arabic script)"),
    ("psu-brah", "Sauraseni Prākrit (Brahmi script)"),
    ("psu-deva", "Sauraseni Prākrit (Devanagari script)"),
    ("psu-guru", "Sauraseni Prākrit (Gurmukhi script)"),
    ("pt", "Portuguese"),
    ("pt-ao1990", "Portuguese (1990 Orthographic Agreement)"),
    ("pt-br", "Brazilian Portuguese"),
    ("pt-colb1945", "Portuguese (1945 Orthographic Agreement)"),
    ("pt-pt", "European Portuguese"),
    ("pwn", "Paiwan"),
    ("pwo", "Western Pwo"),
    ("pyu", "Puyuma"),
    ("pzh", "Pazeh"),
    ("qu", "Quechua"),
    ("quc", "Kʼicheʼ"),
    ("qug", "Chimborazo Highland Quichua"),
    ("qwh", "Huaylas Ancash Quechua"),
    ("qxp", "Puno Quechua"),
    ("qxq", "Qashqai"),
    ("qya", "Quenya"),
    ("rag", "Logooli"),
    ("rah", "Rabha"),
    ("raj", "Rajasthani"),
    ("rap", "Rapanui"),
    ("rar", "Rarotongan"),
    ("rcf", "Réunion Creole French"),
    ("rej", "Rejang"),
    ("rgn", "Romagnol"),
    ("rhg", "Rohingya"),
    ("rhg-arab", "Rohingya (Arabic script)"),
    ("rhg-rohg", "Rohingya (Hanifi Rohingya script)"),
    ("rif", "Riffian"),
    ("rji", "Raji"),
    ("rki", "Arakanese"),
    ("rkt", "Rangpuri"),
    ("rm", "Romansh"),
    ("rm-puter", "Putèr"),
    ("rm-rumgr", "Rumantsch Grischun"),
    ("rm-surmiran", "Surmiran"),
    ("rm-sursilv", "Sursilvan"),
    ("rm-sutsilv", "Sutsilvan"),
    ("rm-vallader", "Vallader"),
    ("rmc", "Carpathian Romani"),
    ("rmf", "Finnish Kalo"),
    ("rmg", "Traveller Norwegian"),
    ("rml", "Baltic Romani"),
    ("rml-cyrl", "Baltic Romani (Cyrillic script)"),
    ("rmn", "Balkan Romani"),
    ("rmo", "Sinte Romani"),
    ("rmw", "Welsh-Romani"),
    ("rmy", "Vlax Romani"),
    ("rn", "Rundi"),
    ("rnp", "Rangpo"),
    ("ro", "Romanian"),
    ("ro-md", "Moldovan Romanian"),
    ("roa", "Romance languages"),
    ("roa-rup", "Aromanian"),
    ("roa-tara", "Tarantino"),
    ("rof", "Rombo"),
    ("rom", "Romany"),
    ("rsk", "Pannonian Rusyn"),
    ("rtm", "Rotuman"),
    ("ru", "Russian"),
    ("ru-petr1708", "Russian (Petrine orthography)"),
    ("rue", "Rusyn"),
    ("rug", "Roviana"),
    ("ruo", "Istro Romanian"),
    ("rup", "Aromanian"),
    ("ruq", "Megleno-Romanian"),
    ("ruq-cyrl", "Megleno-Romanian (Cyrillic script)"),
    ("ruq-latn", "Megleno-Romanian (Latin script)"),
    ("rut", "Rutul"),
    ("rw", "Kinyarwanda"),
    ("rwk", "Rwa"),
    ("rwr", "Marwari (India)"),
    ("rys", "Yaeyama"),
    ("rys-hira", "Yaeyama (Hiragana script)"),
    ("ryu", "Okinawan"),
    ("ryu-hira", "Okinawan (Hiragana script)"),
    ("sa", "Sanskrit"),
    ("sa-sidd", "Sanskrit (Siddham script)"),
    ("sad", "Sandawe"),
    ("sah", "Yakut"),
    ("sai", "South American indigenous languages"),
    ("sal", "Salishan languages"),
    ("sam", "Samaritan Aramaic"),
    ("saq", "Samburu"),
    ("sas", "Sasak"),
    ("sat", "Santali"),
    ("sat-beng", "Santali (Bengali script)"),
    ("sat-latn", "Santali (Latin script)"),
    ("sat-orya", "Santali (Oriya script)"),
    ("saz", "Sourashtra"),
    ("sba", "Ngambay"),
    ("sbp", "Sangu"),
    ("sc", "Sardinian"),
    ("sci", "Sri Lanka Malay"),
    ("scl", "Shina"),
    ("scn", "Sicilian"),
    ("sco", "Scots"),
    ("scz", "Shetlandic"),
    ("sd", "Sindhi"),
    ("sd-deva", "Sindhi (Devanagari script)"),
    ("sd-gujr", "Sindhi (Gujarati script)"),
    ("sd-khoj", "Sindhi (Khojki script)"),
    ("sd-sind", "Sindhi (Khudawadi script)"),
    ("sdc", "Sassarese Sardinian"),
    ("sdh", "Southern Kurdish"),
    ("sdh-arab", "Southern Kurdish (Arabic script)"),
    ("sdh-latn", "Southern Kurdish (Latin script)"),
    ("sdo", "Bukar–Sadong"),
    ("se", "Northern Sami"),
    ("se-fi", "Northern Sami (Finland)"),
    ("se-no", "Northern Sami (Norway)"),
    ("se-se", "Northern Sami (Sweden)"),
    ("sea", "Semai"),
    ("see", "Seneca"),
    ("seh", "Sena"),
    ("sei", "Seri"),
    ("sel", "Selkup"),
    ("sem", "Semitic languages"),
    ("ser", "Serrano"),
    ("ses", "Koyraboro Senni"),
    ("sfb", "French Belgian Sign Language"),
    ("sg", "Sango"),
    ("sga", "Old Irish"),
    ("sgh", "Shughni"),
    ("sgh-arab", "Shughni (Arabic script)"),
    ("sgh-cyrl", "Shughni (Cyrillic script)"),
    ("sgh-latn", "Shughni (Latin script)"),
    ("sgn", "sign languages"),
    ("sgs", "Samogitian"),
    ("sgy-arab", "Sanglechi (Arabic script)"),
    ("sgy-latn", "Sanglechi (Latin script)"),
    ("sh", "Serbo-Croatian"),
    ("sh-cyrl", "Serbo-Croatian (Cyrillic script)"),
    ("sh-latn", "Serbo-Croatian (Latin script)"),
    ("shd", "Kundal Shahi"),
    ("shi", "Tachelhit"),
    ("shi-latn", "Tachelhit (Latin script)"),
    ("shi-tfng", "Tachelhit (Tifinagh script)"),
    ("shn", "Shan"),
    ("shu", "Chadian Arabic"),
    ("shy", "Shawiya"),
    ("shy-arab", "Shawiya (Arabic script)"),
    ("shy-latn", "Shawiya (Latin script)"),
    ("shy-tfng", "Shawiya (Tifinagh script)"),
    ("si", "Sinhala"),
    ("sia", "Akkala Sami"),
    ("sid", "Sidamo"),
    ("simple", "Simple English"),
    ("sio", "Siouan languages"),
    ("sit", "Sino-Tibetan languages"),
    ("sjd", "Kildin Sami"),
    ("sje", "Pite Sami"),
    ("sjk", "Kemi Sami"),
    ("sjn", "Sindarin"),
    ("sjo", "Xibe"),
    ("sjs", "Senhaja De Srair"),
    ("sjt", "Ter Sami"),
    ("sju", "Ume Sami"),
    ("sk", "Slovak"),
    ("skr", "Saraiki"),
    ("skr-arab", "Saraiki (Arabic script)"),
    ("sl", "Slovenian"),
    ("sla", "Slavic languages"),
    ("slh", "Southern Lushootseed"),
    ("sli", "Lower Silesian"),
    ("slr", "Salar"),
    ("sly", "Selayar"),
    ("sm", "Samoan"),
    ("sma", "Southern Sami"),
    ("smi", "Sámi languages"),
    ("smj", "Lule Sami"),
    ("smn", "Inari Sami"),
    ("sms", "Skolt Sami"),
    ("sn", "Shona"),
    ("sne", "Jagoi"),
    ("snk", "Soninke"),
    ("so", "Somali"),
    ("sog", "Sogdien"),
    ("son", "Songhay languages"),
    ("spv", "Sambalpuri"),
    ("sq", "Albanian"),
    ("sr", "Serbian"),
    ("sr-cyrl", "Serbian (Cyrillic script)"),
    ("sr-ec", "Serbian (Cyrillic script)"),
    ("sr-el", "Serbian (Latin script)"),
    ("sr-latn", "Serbian (Latin script)"),
    ("sr-me", "Montenegrin"),
    ("srh-arab", "Sarikoli (Arabic script)"),
    ("srh-cyrl", "Sarikoli (Cyrillic script)"),
    ("srh-latn", "Sarikoli (Latin script)"),
    ("srk", "Serudung"),
    ("srn", "Sranan Tongo"),
    ("sro", "Campidanese Sardinian"),
    ("srq", "Sirionó"),
    ("srr", "Serer"),
    ("ss", "Swati"),
    ("ssa", "Nilo-Saharan languages"),
    ("ssb", "Southern Sama"),
    ("ssf", "Thao"),
    ("ssy", "Saho"),
    ("st", "Southern Sotho"),
    ("sth", "Shelta"),
    ("stq", "Saterland Frisian"),
    ("str", "Straits Salish"),
    ("sty", "Siberian Tatar"),
    ("su", "Sundanese"),
    ("suk", "Sukuma"),
    ("sus", "Susu"),
    ("sux", "Sumerian"),
    ("sux-latn", "Sumerian (Latin script)"),
    ("sux-xsux", "Sumerian (Cuneiform script)"),
    ("suz", "Sunwar"),
    ("sv", "Swedish"),
    ("sva", "Svan"),
    ("svm", "Molise Slavic"),
    ("sw", "Swahili"),
    ("sw-arab", "Swahili (Arabic script)"),
    ("sw-arab-cd", "Swahili (Arabic script, Congo)"),
    ("sw-arab-mz", "Swahili (Arabic script, Mozambique)"),
    ("sw-cd", "Congo Swahili"),
    ("swb", "Comorian"),
    ("sxr", "Saaroa"),
    ("sxu", "Upper Saxon"),
    ("syc", "Classical Syriac"),
    ("syl", "Sylheti"),
    ("syl-beng", "Sylheti (Bengali script)"),
    ("syl-sylo", "Sylheti (Sylheti Nagri script)"),
    ("syr", "Syriac"),
    ("szl", "Silesian"),
    ("szy", "Sakizaya"),
    ("ta", "Tamil"),
    ("tai", "Tai languages"),
    ("tao", "Yami"),
    ("tay", "Atayal"),
    ("tbl", "Tboli"),
    ("tce", "Southern Tutchone"),
    ("tcy", "Tulu"),
    ("tdd", "Tai Nuea"),
    ("te", "Telugu"),
    ("tem", "Timne"),
    ("teo", "Teso"),
    ("ter", "Tereno"),
    ("tet", "Tetum"),
    ("tg", "Tajik"),
    ("tg-cyrl", "Tajik (Cyrillic script)"),
    ("tg-latn", "Tajik (Latin script)"),
    ("tgx", "Tagish"),
    ("th", "Thai"),
    ("thq", "Kochila Tharu"),
    ("thr", "Rana Tharu"),
    ("tht", "Tahltan"),
    ("ti", "Tigrinya"),
    ("tig", "Tigre"),
    ("tih", "Timugon"),
    ("tiv", "Tiv"),
    ("tji", "Northern Tujia"),
    ("tk", "Turkmen"),
    ("tkl", "Tokelauan"),
    ("tkr", "Tsakhur"),
    ("tl", "Tagalog"),
    ("tlb", "Tobelo"),
    ("tlh", "Klingon"),
    ("tlh-latn", "Klingon (Latin script)"),
    ("tlh-piqd", "Klingon (Klingon script)"),
    ("tli", "Tlingit"),
    ("tly", "Talysh"),
    ("tly-cyrl", "Talysh (Cyrillic script)"),
    ("tmh", "Tamashek"),
    ("tmr", "Jewish Babylonian Aramaic"),
    ("tn", "Tswana"),
    ("tnq", "Taíno"),
    ("to", "Tongan"),
    ("tog", "Nyasa Tonga"),
    ("toi", "Tonga (Botatwe)"),
    ("tok", "Toki Pona"),
    ("tpi", "Tok Pisin"),
    ("tr", "Turkish"),
    ("trp", "Kokborok"),
    ("tru", "Turoyo"),
    ("trv", "Taroko"),
    ("trw", "Torwali"),
    ("ts", "Tsonga"),
    ("tsd", "Tsakonian"),
    ("tsg", "Tausug"),
    ("tsi", "Tsimshian"),
    ("tsu", "Tsou"),
    ("tsw", "Tsishingini"),
    ("tt", "Tatar"),
    ("tt-cyrl", "Tatar (Cyrillic script)"),
    ("tt-latn", "Tatar (Latin script)"),
    ("ttj", "Tooro"),
    ("ttm", "Northern Tutchone"),
    ("ttt", "Muslim Tat"),
    ("tui", "Tupuri"),
    ("tum", "Tumbuka"),
    ("tup", "Tupian languages"),
    ("tut", "Altaic languages"),
    ("tvl", "Tuvalu"),
    ("tvu", "Tunen"),
    ("tw", "Twi"),
    ("twd", "Tweants"),
    ("twq", "Tasawaq"),
    ("txa", "Tombonuwo"),
    ("txg", "Tangut"),
    ("txo-beng", "Toto (Bengali script)"),
    ("txo-toto", "Toto (Toto script)"),
    ("txx", "Tatana"),
    ("ty", "Tahitian"),
    ("tyv", "Tuvinian"),
    ("tzl", "Talossan"),
    ("tzm", "Central Atlas Tamazight"),
    ("tzo", "Tzotzil"),
    ("udm", "Udmurt"),
    ("ug", "Uyghur"),
    ("ug-arab", "Uyghur (Arabic script)"),
    ("ug-cyrl", "Uyghur (Cyrillic script)"),
    ("ug-latn", "Uyghur (Latin script)"),
    ("uga", "Ugaritic"),
    ("uk", "Ukrainian"),
    ("ulc", "Ulch"),
    ("uln", "Unserdeutsch"),
    ("umb", "Umbundu"),
    ("umu", "Munsee"),
    ("und", "undetermined language"),
    ("unr", "Mundari"),
    ("unr-deva", "Mundari (Devanagari script)"),
    ("unr-nagm", "Mundari (Nag Mundari script)"),
    ("uon", "Kulon"),
    ("ur", "Urdu"),
    ("urk", "Urak Lawoiʼ"),
    ("ush", "Ushoji"),
    ("uun", "Pazeh"),
    ("uz", "Uzbek"),
    ("uz-cyrl", "Uzbek (Cyrillic script)"),
    ("uz-latn", "Uzbek (Latin script)"),
    ("uzs", "Southern Uzbek"),
    ("vai", "Vai"),
    ("ve", "Venda"),
    ("vec", "Venetian"),
    ("vep", "Veps"),
    ("vgt", "Flemish Sign Language"),
    ("vi", "Vietnamese"),
    ("vi-hani", "Vietnamese (Han script)"),
    ("vls", "West Flemish"),
    ("vls-be", "Belgian Flemish"),
    ("vls-fr", "French Flemish"),
    ("vls-nl", "Dutch Flemish"),
    ("vmf", "Main-Franconian"),
    ("vmw", "Makhuwa"),
    ("vo", "Volapük"),
    ("vot", "Votic"),
    ("vro", "Võro"),
    ("vun", "Vunjo"),
    ("vut", "Vute"),
    ("wa", "Walloon"),
    ("wae", "Walser"),
    ("wak", "Wakashan languages"),
    ("wal", "Wolaytta"),
    ("war", "Waray"),
    ("was", "Washo"),
    ("way", "Wayana"),
    ("wbl-arab", "Wakhi (Arabic script)"),
    ("wbl-arab-af", "Wakhi (Arabic script, Afghanistan)"),
    ("wbl-arab-cn", "Wakhi (Arabic script, China)"),
    ("wbl-arab-pk", "Wakhi (Arabic script, Pakistan)"),
    ("wbl-cyrl", "Wakhi (Cyrillic script)"),
    ("wbl-latn", "Wakhi (Latin script)"),
    ("wbp", "Warlpiri"),
    ("wen", "Sorbian languages"),
    ("wes", "Pidgin (Cameroon)"),
    ("wlm", "Middle Welsh"),
    ("wls", "Wallisian"),
    ("wlx", "Wali"),
    ("wo", "Wolof"),
    ("wsg", "Adilabad Gondi"),
    ("wsv", "Wotapuri-Katarqalai"),
    ("wuu", "Wu"),
    ("wuu-hans", "Wu (Simplified Han script)"),
    ("wuu-hant", "Wu (Traditional Han script)"),
    ("wya", "Wyandot"),
    ("wyi", "Woiwurrung"),
    ("xal", "Kalmyk"),
    ("xbm", "Middle Breton"),
    ("xh", "Xhosa"),
    ("xmf", "Mingrelian"),
    ("xmm", "Manado Malay"),
    ("xnb", "Kanakanavu"),
    ("xno", "Anglo-Norman"),
    ("xnr", "Kangri"),
    ("xnr-deva", "Kangri (Devanagari script)"),
    ("xnr-takr", "Kangri (Takri script)"),
    ("xog", "Soga"),
    ("xon", "Konkomba"),
    ("xpu", "Punic"),
    ("xsu", "Sanumá"),
    ("xsy", "Saisiyat"),
    ("yag", "Yaghan"),
    ("yah-cyrl", "Yazghulami (Cyrillic script)"),
    ("yah-latn", "Yazghulami (Latin script)"),
    ("yai-cyrl", "Yaghnobi (Cyrillic script)"),
    ("yai-latn", "Yaghnobi (Latin script)"),
    ("yao", "Yao"),
    ("yap", "Yapese"),
    ("yas", "Nugunu"),
    ("yat", "Yambeta"),
    ("yav", "Yangben"),
    ("ybb", "Yemba"),
    ("ydd", "Eastern Yiddish"),
    ("ydg", "Yidgha"),
    ("yec", "Yeniche"),
    ("yi", "Yiddish"),
    ("ykg", "Tundra Yukaghir"),
    ("yo", "Yoruba"),
    ("yoi", "Yonaguni"),
    ("yoi-hira", "Yonaguni (Hiragana script)"),
    ("yox", "Yoron"),
    ("yox-hira", "Yoron (Hiragana script)"),
    ("ypk", "Yupik languages"),
    ("yrk", "Nenets"),
    ("yrl", "Nheengatu"),
    ("yua", "Yucatec Maya"),
    ("yue", "Cantonese"),
    ("yue-hans", "Cantonese (Simplified Han script)"),
    ("yue-hant", "Cantonese (Traditional Han script)"),
    ("za", "Zhuang"),
    ("zai", "Isthmus Zapotec"),
    ("zap", "Zapotec"),
    ("zbl", "Blissymbols"),
    ("zea", "Zeelandic"),
    ("zen", "Zenaga"),
    ("zgh", "Standard Moroccan Tamazight"),
    ("zgh-latn", "Standard Moroccan Tamazight (Latin script)"),
    ("zh", "Chinese"),
    ("zh-classical", "Literary Chinese"),
    ("zh-cn", "Chinese (China)"),
    ("zh-hans", "Simplified Chinese"),
    ("zh-hant", "Traditional Chinese"),
    ("zh-hk", "Chinese (Hong Kong)"),
    ("zh-min-nan", "Minnan"),
    ("zh-mo", "Chinese (Macau)"),
    ("zh-my", "Chinese (Malaysia)"),
    ("zh-sg", "Chinese (Singapore)"),
    ("zh-tw", "Chinese (Taiwan)"),
    ("zh-yue", "Cantonese"),
    ("zmi", "Negeri Sembilan Malay"),
    ("znd", "Zande languages"),
    ("zpu", "Yalálag Zapotec"),
    ("zu", "Zulu"),
    ("zun", "Zuni"),
    ("zxx", "no linguistic content"),
    ("zza", "Zaza"),
];
