//! Serializer `WTSUtils`/`WTUtils` leaf helpers and DOM predicates.
//!
//! Faithful ports of the pure, state-free helpers from PHP's
//! `Html2Wt/WTSUtils.php` and `Utils/WTUtils.php` that the html2wt serializer
//! and its escape/separator logic depend on. These operate on our semantic
//! `Node`/`DomTree` (by `NodeId`) and are the leaf layer beneath
//! `SerializerState`/`Separators`/`WikitextEscapeHandlers`.

use crate::dom::node::{ElementKind, Node, NodeKind};

/// Map an `ElementKind` to its HTML tag name. Consolidates the identical
/// mapping previously duplicated in `cleanup`, `p_wrap`, and `serialize`.
pub fn element_tag(kind: &ElementKind) -> String {
    match kind {
        ElementKind::Document => "html".to_string(),
        ElementKind::Paragraph => "p".to_string(),
        ElementKind::Heading(1) => "h1".to_string(),
        ElementKind::Heading(2) => "h2".to_string(),
        ElementKind::Heading(3) => "h3".to_string(),
        ElementKind::Heading(4) => "h4".to_string(),
        ElementKind::Heading(5) => "h5".to_string(),
        ElementKind::Heading(6) => "h6".to_string(),
        ElementKind::Heading(n) => format!("h{n}"),
        ElementKind::Bold => "b".to_string(),
        ElementKind::Italic => "i".to_string(),
        ElementKind::Wikilink | ElementKind::ExtLink => "a".to_string(),
        ElementKind::Image => "figure-inline".to_string(),
        ElementKind::Gallery => "ul".to_string(),
        ElementKind::Table => "table".to_string(),
        ElementKind::TableRow => "tr".to_string(),
        ElementKind::TableCell => "td".to_string(),
        ElementKind::TableHeader => "th".to_string(),
        ElementKind::TableCaption => "caption".to_string(),
        ElementKind::UnorderedList => "ul".to_string(),
        ElementKind::OrderedList => "ol".to_string(),
        ElementKind::ListItem => "li".to_string(),
        ElementKind::DefinitionList => "dl".to_string(),
        ElementKind::DefinitionTerm => "dt".to_string(),
        ElementKind::DefinitionDescription => "dd".to_string(),
        ElementKind::Preformatted => "pre".to_string(),
        ElementKind::HorizontalRule => "hr".to_string(),
        ElementKind::Transclusion | ElementKind::Annotation => "meta".to_string(),
        ElementKind::ExtensionTag | ElementKind::Span => "span".to_string(),
        ElementKind::Div => "div".to_string(),
        ElementKind::LineBreak => "br".to_string(),
        ElementKind::Comment => "comment".to_string(),
        ElementKind::RawHtml => "raw".to_string(),
        ElementKind::Section => "section".to_string(),
        ElementKind::InterlanguageLink | ElementKind::CategoryLink | ElementKind::Redirect => {
            "link".to_string()
        }
        ElementKind::TableOfContents => "div".to_string(),
        ElementKind::Indicator => "meta".to_string(),
        ElementKind::Figure => "figure".to_string(),
        ElementKind::FigCaption => "figcaption".to_string(),
        ElementKind::Other(tag) => tag.clone(),
    }
}

/// The HTML tag name of a node, or `""` for non-element nodes.
pub fn node_name(node: &Node) -> String {
    match &node.kind {
        NodeKind::Element(kind) => element_tag(kind),
        _ => String::new(),
    }
}

/// Whether a node's `data-parsoid` has `stx === 'html'` (a literal HTML element
/// in the source). Mirrors `WTUtils::hasLiteralHTMLMarker`/`isLiteralHTMLNode`.
pub fn is_literal_html_node(node: &Node) -> bool {
    matches!(&node.kind, NodeKind::Element(_))
        && node
            .data_parsoid
            .as_deref()
            .is_some_and(|dp| dp.contains("\"stx\":\"html\""))
}

/// Whether a node is a "zero-width wikitext element" (generated by Parsoid,
/// with no visible wikitext source of its own). Mirrors
/// `WTUtils::isZeroWidthWikitextElt`, using the faithful
/// `Consts::$ZeroWidthWikitextTags` set.
pub fn is_zero_width_wikitext_elt(node: &Node) -> bool {
    match &node.kind {
        NodeKind::Element(kind) => {
            crate::wikitext::consts::zero_width_wikitext_tags().contains(&element_tag(kind))
                && !is_literal_html_node(node)
        }
        _ => false,
    }
}

/// Whether a node is a *_start_* encapsulation wrapper (the first element of
/// an encapsulated range carrying `about`/`typeof`). Mirrors
/// `WTUtils::isFirstEncapsulationWrapperNode` (`FIRST_ENCAP_REGEXP`).
pub fn is_first_encapsulation_wrapper_node(node: &Node) -> bool {
    node.get_attr("about").is_some()
        && node.get_attr("typeof").is_some_and(|ty| {
            ty.split_whitespace().any(|t| {
                t == "mw:Transclusion"
                    || t == "mw:Param"
                    || t == "mw:LanguageVariant"
                    || t.starts_with("mw:Extension/")
            })
        })
}

/// Whether a node is a "moved" annotation meta (its `data-parsoid` carries
/// `wasMoved`). Mirrors `WTUtils::isMovedMetaTag`.
pub fn is_moved_meta_tag(node: &Node) -> bool {
    matches!(node.kind, NodeKind::Element(ElementKind::Annotation))
        && node
            .data_parsoid
            .as_deref()
            .is_some_and(|dp| dp.contains("\"wasMoved\":true"))
}

/// Whether a node is a quote element (`<b>` or `<i>`). Mirrors
/// `DOMUtils::isQuoteElt`.
pub fn is_quote_elt(node: &Node) -> bool {
    matches!(
        node.kind,
        NodeKind::Element(ElementKind::Bold) | NodeKind::Element(ElementKind::Italic)
    )
}

/// Escape `<nowiki>` tags (so they tokenize as literal text rather than
/// nowiki markup). Mirrors `WTSUtils::escapeNowikiTags`.
pub fn escape_nowiki_tags(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        // Match `<nowiki>`, `</nowiki>`, `<nowiki/>`, `</ nowiki>`, etc.,
        // case-insensitively, mirroring the PHP `#<(/?nowiki\s*/?\s*)>#i`.
        if bytes[i] == b'<' {
            let rest = &text[i..];
            let lower = rest.to_ascii_lowercase();
            if let Some(idx) = lower.find('>') {
                let inner = &lower[1..idx];
                let inner_trim = inner.trim();
                let is_nowiki = inner_trim.starts_with("/")
                    && inner_trim[1..]
                        .trim_start()
                        .trim_end()
                        .starts_with("nowiki")
                    || inner_trim.starts_with("nowiki");
                if is_nowiki {
                    let orig = &rest[..idx + 1];
                    out.push_str("&lt;");
                    out.push_str(&orig[1..orig.len() - 1]);
                    out.push_str("&gt;");
                    i += idx + 1;
                    continue;
                }
            }
        }
        let ch_len = crate::util::utf8_len_public(bytes[i]);
        out.push_str(&text[i..i + ch_len]);
        i += ch_len;
    }
    out
}

/// Whether `sep` is a valid separator string (whitespace/comments only).
/// Mirrors `WTSUtils::isValidSep`.
pub fn is_valid_sep(sep: &str) -> bool {
    // `^(\s|<!--([^\-]|-(?!->))*-->)*$` — whitespace or well-formed comments.
    let mut i = 0;
    let bytes = sep.as_bytes();
    while i < bytes.len() {
        if sep[i..].starts_with("<!--") {
            // Find the terminating `-->`.
            match sep[i + 4..].find("-->") {
                Some(end) => i += 4 + end + 3,
                None => return false,
            }
        } else if bytes[i].is_ascii_whitespace() {
            i += 1;
        } else {
            return false;
        }
    }
    true
}

/// Convert a DOM-escaped comment value back to its wikitext form (including
/// `<!--`/`-->`). Mirrors `WTSUtils::commentWT` + `WTUtils::decodeComment`.
pub fn comment_wt(comment: &str) -> String {
    format!("<!--{}-->", decode_comment(comment))
}

/// Map an HTML DOM-escaped comment to a wikitext-escaped comment, so `-->`
/// never appears literally. Mirrors `WTUtils::decodeComment`.
pub fn decode_comment(comment: &str) -> String {
    // Undo HTML entity escaping (true value), then re-encode `--(>|&…gt;)`
    // so the literal `-->` sequence can't terminate the wikitext comment.
    let true_value = decode_wt_entities_all(comment);
    encode_comment_gt(&true_value)
}

/// Decode every `&…;` entity in `text` (leaving non-entities unchanged).
/// Mirrors PHP's `Utils::decodeWtEntities` applied over a whole string.
fn decode_wt_entities_all(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'&'
            && let Some((j, _)) = text[i..].char_indices().find(|(_, c)| *c == ';')
        {
            let end = i + j; // byte offset of ';' relative to text
            let entity = &text[i..=end];
            let decoded = crate::wikitext::tokenizer_v2::decode_wt_entities(entity);
            if decoded != entity {
                out.push_str(&decoded);
                i = end + 1;
                continue;
            }
        }
        let ch_len = crate::util::utf8_len_public(bytes[i]);
        out.push_str(&text[i..i + ch_len]);
        i += ch_len;
    }
    out
}

/// Encode `--(>|&(amp;)*gt;)` so no literal `-->` appears. Faithful to the
/// tail of `WTUtils::decodeComment`.
fn encode_comment_gt(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    let bytes = s.as_bytes();
    while i < bytes.len() {
        if s[i..].starts_with("-->") {
            out.push_str("--&gt;");
            i += 3;
        } else if s[i..].starts_with("--") {
            // `--&(amp;)*gt;` → `--&amp;` + rest.
            let rest = &s[i + 2..];
            if rest.starts_with('>') || rest.starts_with('&') {
                out.push_str("--&amp;");
                out.push_str(&rest[..1.min(rest.len())]);
                i += 3;
                continue;
            }
            // Plain `--` (not followed by `>` or `&`) — copy one char.
            out.push('-');
            i += 1;
        } else {
            let ch_len = crate::util::utf8_len_public(bytes[i]);
            out.push_str(&s[i..i + ch_len]);
            i += ch_len;
        }
    }
    out
}

/// `WTUtils::isGeneratedFigure` — `typeof` matches `#^mw:File($|/)#D`.
pub fn is_generated_figure(node: &Node) -> bool {
    crate::html::dom_utils::match_type_of(node, "^mw:File($|/)").is_some()
}

/// `WTUtils::isInlineMedia` — a `<span>` that is a generated figure.
pub fn is_inline_media(node: &Node) -> bool {
    node_name(node) == "span" && is_generated_figure(node)
}

/// `WTUtils::getMediaFormat` — the `/Format` suffix of a `mw:File/…` `typeof`
/// (empty string when none).
pub fn get_media_format(node: &Node) -> String {
    let media_type = crate::html::dom_utils::match_type_of(node, "^mw:File($|/)");
    match media_type {
        Some(ty) => ty.split('/').nth(1).unwrap_or("").to_string(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_escape_nowiki_tags() {
        assert_eq!(
            escape_nowiki_tags("<nowiki>x</nowiki>"),
            "&lt;nowiki&gt;x&lt;/nowiki&gt;"
        );
        assert_eq!(escape_nowiki_tags("plain"), "plain");
        assert_eq!(escape_nowiki_tags("a <b> c"), "a <b> c"); // non-nowiki untouched
    }

    #[test]
    fn test_is_valid_sep() {
        assert!(is_valid_sep(" \n\t"));
        assert!(is_valid_sep(" <!-- c --> \n"));
        assert!(!is_valid_sep("x"));
        assert!(!is_valid_sep("<!-- unclosed"));
    }

    #[test]
    fn test_comment_wt() {
        assert_eq!(comment_wt("foo"), "<!--foo-->");
        assert_eq!(comment_wt("a --> b"), "<!--a --&gt; b-->");
    }

    #[test]
    fn test_element_tag() {
        assert_eq!(element_tag(&ElementKind::Paragraph), "p");
        assert_eq!(element_tag(&ElementKind::Heading(3)), "h3");
        assert_eq!(element_tag(&ElementKind::Bold), "b");
    }

    #[test]
    fn test_is_quote_elt() {
        assert!(is_quote_elt(&Node::element(ElementKind::Italic)));
        assert!(is_quote_elt(&Node::element(ElementKind::Bold)));
        assert!(!is_quote_elt(&Node::element(ElementKind::Paragraph)));
    }
}
