//! Serializer `WTSUtils`/`WTUtils` leaf helpers and DOM predicates.
//!
//! Faithful ports of the pure, state-free helpers from PHP's
//! `Html2Wt/WTSUtils.php` and `Utils/WTUtils.php` that the html2wt serializer
//! and its escape/separator logic depend on. These operate on our semantic
//! `Node`/`DomTree` (by `NodeId`) and are the leaf layer beneath
//! `SerializerState`/`Separators`/`WikitextEscapeHandlers`.

use crate::dom::node::{ElementKind, Node, NodeKind};

/// Shadow-attribute info, mirroring PHP's `WTSUtils::getShadowInfo` result:
/// `['value' => …, 'modified' => bool, 'fromsrc' => bool]`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ShadowInfo {
    /// The attribute value to serialize (may differ from the DOM attribute).
    pub value: String,
    /// Did the value change since the wikitext was parsed?
    pub modified: bool,
    /// Was the value recovered from source-based round-tripping (`dp->sa`)?
    pub fromsrc: bool,
}

/// Map an `ElementKind` to its HTML tag name. Consolidates the identical
/// mapping previously duplicated in `cleanup`, `p_wrap`, and `serialize`.
pub fn element_tag(kind: &ElementKind) -> String {
    match kind {
        ElementKind::Document => "html".to_string(),
        ElementKind::Paragraph => "p".to_string(),
        ElementKind::Heading(1) => "h1".to_string(),
        ElementKind::Heading(2) => "h2".to_string(),
        ElementKind::Heading(3) => "h3".to_string(),
        ElementKind::Heading(4) => "h4".to_string(),
        ElementKind::Heading(5) => "h5".to_string(),
        ElementKind::Heading(6) => "h6".to_string(),
        ElementKind::Heading(n) => format!("h{n}"),
        ElementKind::Bold => "b".to_string(),
        ElementKind::Italic => "i".to_string(),
        ElementKind::Wikilink | ElementKind::ExtLink => "a".to_string(),
        ElementKind::Image => "figure-inline".to_string(),
        ElementKind::Gallery => "ul".to_string(),
        ElementKind::Table => "table".to_string(),
        ElementKind::TableRow => "tr".to_string(),
        ElementKind::TableCell => "td".to_string(),
        ElementKind::TableHeader => "th".to_string(),
        ElementKind::TableCaption => "caption".to_string(),
        ElementKind::UnorderedList => "ul".to_string(),
        ElementKind::OrderedList => "ol".to_string(),
        ElementKind::ListItem => "li".to_string(),
        ElementKind::DefinitionList => "dl".to_string(),
        ElementKind::DefinitionTerm => "dt".to_string(),
        ElementKind::DefinitionDescription => "dd".to_string(),
        ElementKind::Preformatted => "pre".to_string(),
        ElementKind::HorizontalRule => "hr".to_string(),
        ElementKind::Transclusion | ElementKind::Annotation => "meta".to_string(),
        ElementKind::ExtensionTag | ElementKind::Span => "span".to_string(),
        ElementKind::Div => "div".to_string(),
        ElementKind::LineBreak => "br".to_string(),
        ElementKind::Comment => "comment".to_string(),
        ElementKind::RawHtml => "raw".to_string(),
        ElementKind::Section => "section".to_string(),
        ElementKind::InterlanguageLink | ElementKind::CategoryLink | ElementKind::Redirect => {
            "link".to_string()
        }
        ElementKind::TableOfContents => "div".to_string(),
        ElementKind::Indicator => "meta".to_string(),
        ElementKind::Figure => "figure".to_string(),
        ElementKind::FigCaption => "figcaption".to_string(),
        ElementKind::Other(tag) => tag.clone(),
    }
}

/// The HTML tag name of a node, or `""` for non-element nodes.
pub fn node_name(node: &Node) -> String {
    match &node.kind {
        NodeKind::Element(kind) => element_tag(kind),
        _ => String::new(),
    }
}

/// Whether a node's `data-parsoid` has `stx === 'html'` (a literal HTML element
/// in the source). Mirrors `WTUtils::hasLiteralHTMLMarker`/`isLiteralHTMLNode`.
pub fn is_literal_html_node(node: &Node) -> bool {
    matches!(&node.kind, NodeKind::Element(_))
        && (node
            .dp
            .as_ref()
            .is_some_and(|dp| dp.stx.as_deref() == Some("html"))
            // Fallback for nodes loaded from serialized `data-parsoid` JSON
            // (the html2wt path), where only the raw blob is available.
            || node
                .data_parsoid
                .as_deref()
                .is_some_and(|dp| dp.contains("\"stx\":\"html\"")))
}

/// Whether a node is a "zero-width wikitext element" (generated by Parsoid,
/// with no visible wikitext source of its own). Mirrors
/// `WTUtils::isZeroWidthWikitextElt`, using the faithful
/// `Consts::$ZeroWidthWikitextTags` set.
pub fn is_zero_width_wikitext_elt(node: &Node) -> bool {
    match &node.kind {
        NodeKind::Element(kind) => {
            crate::wikitext::consts::zero_width_wikitext_tags().contains(&element_tag(kind))
                && !is_literal_html_node(node)
        }
        _ => false,
    }
}

/// Whether a node is a *_start_* encapsulation wrapper (the first element of
/// an encapsulated range carrying `about`/`typeof`). Mirrors
/// `WTUtils::isFirstEncapsulationWrapperNode` (`FIRST_ENCAP_REGEXP`).
pub fn is_first_encapsulation_wrapper_node(node: &Node) -> bool {
    node.get_attr("about").is_some()
        && node.get_attr("typeof").is_some_and(|ty| {
            ty.split_whitespace().any(|t| {
                t == "mw:Transclusion"
                    || t == "mw:Param"
                    || t == "mw:LanguageVariant"
                    || t.starts_with("mw:Extension/")
            })
        })
}

/// Whether a node is a "moved" annotation meta (its `data-parsoid` carries
/// `wasMoved`). Mirrors `WTUtils::isMovedMetaTag`.
pub fn is_moved_meta_tag(node: &Node) -> bool {
    matches!(node.kind, NodeKind::Element(ElementKind::Annotation))
        && node
            .data_parsoid
            .as_deref()
            .is_some_and(|dp| dp.contains("\"wasMoved\":true"))
}

/// Whether a node is a quote element (`<b>` or `<i>`). Mirrors
/// `DOMUtils::isQuoteElt`.
pub fn is_quote_elt(node: &Node) -> bool {
    matches!(
        node.kind,
        NodeKind::Element(ElementKind::Bold) | NodeKind::Element(ElementKind::Italic)
    )
}

/// The DOM Source Range (`data-parsoid.dsr`) of a node as the serializer-facing
/// [`DomSourceRange`](crate::html::dsr::DomSourceRange), or `None` when the node
/// has no structured `data-parsoid`/`dsr`. Faithful to
/// `DOMDataUtils::getDataParsoid($node)->dsr`.
///
/// The tokenizer stores DSR as `tokens_v2::DomSourceRange` (without the
/// html2wt-only `source`/trimmed-WS fields); this lifts it into the serializer's
/// richer model, leaving `source` empty for `getOrigSrc` to supply.
pub fn get_dsr(node: &Node) -> Option<crate::html::dsr::DomSourceRange> {
    node.dp.as_ref()?.dsr.clone().map(Into::into)
}

/// `WTSUtils::hasValidTagWidths` — non-null DSR with valid tag widths.
pub fn has_valid_tag_widths(dsr: Option<&crate::html::dsr::DomSourceRange>) -> bool {
    dsr.is_some_and(|d| d.has_valid_tag_widths())
}

/// Escape `<nowiki>` tags (so they tokenize as literal text rather than
/// nowiki markup). Mirrors `WTSUtils::escapeNowikiTags`.
pub fn escape_nowiki_tags(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        // Match `<nowiki>`, `</nowiki>`, `<nowiki/>`, `</ nowiki>`, etc.,
        // case-insensitively, mirroring the PHP `#<(/?nowiki\s*/?\s*)>#i`.
        if bytes[i] == b'<' {
            let rest = &text[i..];
            let lower = rest.to_ascii_lowercase();
            if let Some(idx) = lower.find('>') {
                let inner = &lower[1..idx];
                let inner_trim = inner.trim();
                let is_nowiki = inner_trim.starts_with("/")
                    && inner_trim[1..]
                        .trim_start()
                        .trim_end()
                        .starts_with("nowiki")
                    || inner_trim.starts_with("nowiki");
                if is_nowiki {
                    let orig = &rest[..idx + 1];
                    out.push_str("&lt;");
                    out.push_str(&orig[1..orig.len() - 1]);
                    out.push_str("&gt;");
                    i += idx + 1;
                    continue;
                }
            }
        }
        let ch_len = crate::util::utf8_len_public(bytes[i]);
        out.push_str(&text[i..i + ch_len]);
        i += ch_len;
    }
    out
}

/// Whether `sep` is a valid separator string (whitespace/comments only).
/// Mirrors `WTSUtils::isValidSep`.
pub fn is_valid_sep(sep: &str) -> bool {
    // `^(\s|<!--([^\-]|-(?!->))*-->)*$` — whitespace or well-formed comments.
    let mut i = 0;
    let bytes = sep.as_bytes();
    while i < bytes.len() {
        if sep[i..].starts_with("<!--") {
            // Find the terminating `-->`.
            match sep[i + 4..].find("-->") {
                Some(end) => i += 4 + end + 3,
                None => return false,
            }
        } else if bytes[i].is_ascii_whitespace() {
            i += 1;
        } else {
            return false;
        }
    }
    true
}

/// Convert a DOM-escaped comment value back to its wikitext form (including
/// `<!--`/`-->`). Mirrors `WTSUtils::commentWT` + `WTUtils::decodeComment`.
pub fn comment_wt(comment: &str) -> String {
    format!("<!--{}-->", decode_comment(comment))
}

/// Map an HTML DOM-escaped comment to a wikitext-escaped comment, so `-->`
/// never appears literally. Mirrors `WTUtils::decodeComment`.
pub fn decode_comment(comment: &str) -> String {
    // Undo HTML entity escaping (true value), then re-encode `--(>|&…gt;)`
    // so the literal `-->` sequence can't terminate the wikitext comment.
    let true_value = decode_wt_entities_all(comment);
    encode_comment_gt(&true_value)
}

/// Decode every `&…;` entity in `text` (leaving non-entities unchanged).
/// Mirrors PHP's `Utils::decodeWtEntities` applied over a whole string.
pub(crate) fn decode_wt_entities_all(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'&'
            && let Some((j, _)) = text[i..].char_indices().find(|(_, c)| *c == ';')
        {
            let end = i + j; // byte offset of ';' relative to text
            let entity = &text[i..=end];
            let decoded = crate::wikitext::tokenizer_v2::decode_wt_entities(entity);
            if decoded != entity {
                out.push_str(&decoded);
                i = end + 1;
                continue;
            }
        }
        let ch_len = crate::util::utf8_len_public(bytes[i]);
        out.push_str(&text[i..i + ch_len]);
        i += ch_len;
    }
    out
}

/// Encode `--(>|&(amp;)*gt;)` so no literal `-->` appears. Faithful to the
/// tail of `WTUtils::decodeComment`.
fn encode_comment_gt(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    let bytes = s.as_bytes();
    while i < bytes.len() {
        if s[i..].starts_with("-->") {
            out.push_str("--&gt;");
            i += 3;
        } else if s[i..].starts_with("--") {
            // `--&(amp;)*gt;` → `--&amp;` + rest.
            let rest = &s[i + 2..];
            if rest.starts_with('>') || rest.starts_with('&') {
                out.push_str("--&amp;");
                out.push_str(&rest[..1.min(rest.len())]);
                i += 3;
                continue;
            }
            // Plain `--` (not followed by `>` or `&`) — copy one char.
            out.push('-');
            i += 1;
        } else {
            let ch_len = crate::util::utf8_len_public(bytes[i]);
            out.push_str(&s[i..i + ch_len]);
            i += ch_len;
        }
    }
    out
}

/// `WTUtils::getExtTagName` — the lowercase extension tag name from an
/// `mw:Extension/…` `typeof` token, or `None`.
pub fn get_ext_tag_name(node: &Node) -> Option<String> {
    let matched = crate::html::dom_utils::match_type_of(node, "^mw:Extension/(.+?)$")?;
    matched
        .strip_prefix("mw:Extension/")
        .map(|name| name.to_lowercase())
}

/// `WTUtils::isGeneratedFigure` — `typeof` matches `#^mw:File($|/)#D`.
pub fn is_generated_figure(node: &Node) -> bool {
    crate::html::dom_utils::match_type_of(node, "^mw:File($|/)").is_some()
}

/// `WTUtils::isInlineMedia` — a `<span>` that is a generated figure.
pub fn is_inline_media(node: &Node) -> bool {
    node_name(node) == "span" && is_generated_figure(node)
}

/// `WTUtils::getMediaFormat` — the `/Format` suffix of a `mw:File/…` `typeof`
/// (empty string when none).
pub fn get_media_format(node: &Node) -> String {
    let media_type = crate::html::dom_utils::match_type_of(node, "^mw:File($|/)");
    match media_type {
        Some(ty) => ty.split('/').nth(1).unwrap_or("").to_string(),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// Annotation metas: `WTUtils::matchAnnotationMeta` / `isAnnotation*MarkerMeta` /
// `isMarkerAnnotation` / `extractAnnotationType`.
//
// PHP's `ANNOTATION_META_TYPE_REGEXP = '#^mw:(?:Annotation/([\w\d]+))(?:/End)?$#uD'`.
// ---------------------------------------------------------------------------

/// Return the `mw:Annotation/<name>` `typeof` token (including optional `/End`),
/// or `None`. Mirrors `WTUtils::matchAnnotationMeta`.
fn match_annotation_meta_token(node: &Node) -> Option<String> {
    let ty = node.get_attr("typeof")?;
    ty.split(' ')
        .find(|t| t.starts_with("mw:Annotation/"))
        .map(str::to_string)
}

/// `WTUtils::extractAnnotationType` — the annotation name (without `mw:Annotation/`
/// or `/End`), setting `is_start` to whether it is a start marker.
pub fn extract_annotation_type(node: &Node, is_start: &mut bool) -> Option<String> {
    let token = match_annotation_meta_token(node)?;
    let rest = token.strip_prefix("mw:Annotation/")?;
    *is_start = !rest.ends_with("/End");
    let name = if *is_start {
        rest
    } else {
        rest.strip_suffix("/End").unwrap_or(rest)
    };
    Some(name.to_string())
}

/// `WTUtils::isAnnotationStartMarkerMeta`.
pub fn is_annotation_start_marker_meta(node: &Node) -> bool {
    let mut is_start = false;
    extract_annotation_type(node, &mut is_start).is_some() && is_start
}

/// `WTUtils::isAnnotationEndMarkerMeta`.
pub fn is_annotation_end_marker_meta(node: &Node) -> bool {
    let mut is_start = false;
    let t = extract_annotation_type(node, &mut is_start);
    t.is_some() && !is_start
}

/// `WTUtils::isMarkerAnnotation` — is this a start or end annotation meta?
pub fn is_marker_annotation(node: &Node) -> bool {
    is_annotation_start_marker_meta(node) || is_annotation_end_marker_meta(node)
}

/// The `data-mw.src` field (for `mw:Includes/IncludeOnly`), parsed from the raw
/// `data-mw` JSON blob on the node.
pub fn get_data_mw_src(node: &Node) -> Option<String> {
    let json = node.data_mw.as_deref()?;
    let value: serde_json::Value = serde_json::from_str(json).ok()?;
    value
        .get("src")
        .and_then(|v| v.as_str())
        .map(str::to_string)
}

// ---------------------------------------------------------------------------
// Shadow attributes: `WTSUtils::getShadowInfo` / `getAttributeShadowInfo`.
// ---------------------------------------------------------------------------

/// Whether a node is genuinely new (no `dsr`), mirroring `WTUtils::isNewElt` for
/// the `getShadowInfo` fast path. Operates directly on `node.dp` (no tree).
fn node_is_new(node: &Node) -> bool {
    node.dp.as_ref().is_none_or(|dp| dp.dsr.is_none())
}

/// `WTSUtils::getShadowInfo` — resolve an attribute's shadowed value. Faithful
/// to PHP's `getShadowInfo`, using `data-parsoid`'s `a`/`sa` shadow maps.
pub fn get_shadow_info(node: &Node, name: &str, cur_val: Option<&str>) -> ShadowInfo {
    let cur_val = cur_val.unwrap_or("");
    let dp = node.dp.as_ref();

    // No `a` shadow entry for `name` → plain round-trip.
    if dp
        .and_then(|d| d.a.as_ref())
        .is_none_or(|a| !a.contains_key(name))
    {
        return ShadowInfo {
            value: cur_val.to_string(),
            modified: node_is_new(node),
            fromsrc: false,
        };
    }

    // `a[name] !== curVal` → the attribute changed.
    let a_val = dp.map(|d| d.a.as_ref().unwrap().get(name).unwrap().as_str());
    if a_val != Some(cur_val) {
        return ShadowInfo {
            value: cur_val.to_string(),
            modified: true,
            fromsrc: false,
        };
    }

    // No `sa` shadow entry → unmodified, but not from source.
    if dp
        .and_then(|d| d.sa.as_ref())
        .is_none_or(|sa| !sa.contains_key(name))
    {
        return ShadowInfo {
            value: cur_val.to_string(),
            modified: false,
            fromsrc: false,
        };
    }

    // Full shadow: use the source value.
    ShadowInfo {
        value: dp
            .map(|d| d.sa.as_ref().unwrap().get(name).unwrap().clone())
            .unwrap_or_default(),
        modified: false,
        fromsrc: true,
    }
}

/// `WTSUtils::getAttributeShadowInfo` — [`get_shadow_info`] using the node's
/// current attribute value.
pub fn get_attribute_shadow_info(node: &Node, name: &str) -> ShadowInfo {
    get_shadow_info(node, name, node.get_attr(name))
}

/// `WTUtils::isRedirectLink` — a `<link>` element whose `rel` matches
/// `mw:PageProp/redirect` as a word-bounded token.
pub fn is_redirect_link(node: &Node) -> bool {
    matches!(node.kind, NodeKind::Element(_))
        && node_name(node) == "link"
        && crate::html::dom_utils::match_rel(node, r"\bmw:PageProp/redirect\b").is_some()
}

/// `TokenUtils::SOL_TRANSPARENT_LINK_REGEX` — a `<link>` whose `rel` is a
/// page-prop category/redirect/language link (rendering-transparent / SOL).
fn is_sol_transparent_link(node: &Node) -> bool {
    matches!(node.kind, NodeKind::Element(_))
        && node_name(node) == "link"
        && crate::html::dom_utils::match_rel(
            node,
            r"\bmw:PageProp/(?:Category|redirect|Language)\b",
        )
        .is_some()
}

/// `WTUtils::isFallbackIdSpan` — a `<span typeof="mw:FallbackId">`.
pub fn is_fallback_id_span(node: &Node) -> bool {
    matches!(node.kind, NodeKind::Element(_))
        && node_name(node) == "span"
        && crate::html::dom_utils::has_type_of(node, "mw:FallbackId")
}

/// `WTUtils::isRenderingTransparentNode` — metadata-like nodes that don't show
/// up in output rendering (comments, SOL-transparent links, non-HTML metas, and
/// fallback-id spans).
pub fn is_rendering_transparent_node(node: &Node) -> bool {
    match &node.kind {
        NodeKind::Comment(_) => true,
        _ if is_sol_transparent_link(node) => true,
        NodeKind::Element(_) => {
            let is_meta = node_name(node) == "meta";
            let is_non_html_meta = is_meta
                && !is_marker_annotation(node)
                && !crate::html::dom_utils::has_type_of(node, "mw:DOMFragment")
                && node
                    .dp
                    .as_ref()
                    .is_none_or(|dp| dp.stx.as_deref() != Some("html"));
            is_non_html_meta || is_fallback_id_span(node)
        }
        _ => false,
    }
}

/// `WTUtils::emitsSolTransparentSingleLineWT` — the node emits wikitext that is
/// SOL-transparent and single-line (whitespace text, or a rendering-transparent
/// node).
pub fn emits_sol_transparent_single_line_wt(node: &Node) -> bool {
    match &node.kind {
        NodeKind::Text(t) => !t.is_empty() && t.chars().all(|c| c == ' ' || c == '\t'),
        _ => is_rendering_transparent_node(node),
    }
}

/// `DOMUtils::isNestedListOrListItem` — a list or list-item that is nested
/// inside a list item (requires ancestor navigation).
pub fn is_nested_list_or_list_item(
    tree: &crate::html::dom_tree::DomTree,
    id: crate::html::dom_tree::NodeId,
) -> bool {
    let node = tree.node(id);
    let is_list_or_item =
        crate::html::dom_utils::is_list(node) || crate::html::dom_utils::is_list_item(node);
    if !is_list_or_item {
        return false;
    }
    crate::html::dom_utils::is_nested_in_list_item(tree, id)
}

/// `WTSUtils::nextToDeletedBlockNodeInWT` — is `id` adjacent (in wikitext
/// terms) to a deleted block node, looking past SOL-transparent nodes?
pub fn next_to_deleted_block_node_in_wt(
    tree: &crate::html::dom_tree::DomTree,
    id: crate::html::dom_tree::NodeId,
    before: bool,
) -> bool {
    if crate::html::dom_utils::at_the_top(tree, id) {
        return false;
    }
    let mut orig = id;
    loop {
        // Find the nearest node that shows up in HTML.
        let mut cur: Option<crate::html::dom_tree::NodeId> = Some(orig);
        loop {
            cur = cur.and_then(|c| {
                if before {
                    tree.prev_sibling(c)
                } else {
                    tree.next_sibling(c)
                }
            });
            let Some(c) = cur else { break };
            let node = tree.node(c);
            if crate::html::diff_utils::DiffUtils::maybe_deleted_node(node) {
                return crate::html::diff_utils::DiffUtils::is_deleted_block_node(node);
            }
            if !emits_sol_transparent_single_line_wt(node) {
                // This sibling is not transparent; it is the adjacent node.
                break;
            }
        }

        if cur.is_some() {
            return false;
        }

        // Walk up past zero-width wikitext parents.
        let Some(parent) = tree.parent(orig) else {
            return false;
        };
        if !is_zero_width_wikitext_elt(tree.node(parent)) {
            return false;
        }
        orig = parent;
    }
}

/// `WTSUtils::dsrContainsOpenExtendedRangeAnnotationTag` — does the wikitext
/// pointed at by `node`'s inner DSR contain an opening/closing annotation tag
/// for any *extended* open annotation range?
pub fn dsr_contains_open_extended_range_annotation_tag(
    state: &crate::html::serializer_state::SerializerState,
    node: &Node,
) -> bool {
    if state.open_annotations.is_empty() || !matches!(node.kind, NodeKind::Element(_)) {
        return false;
    }
    let Some(dsr) = get_dsr(node) else {
        return false;
    };
    let Some(src) = state.get_orig_src(&dsr.inner_range()) else {
        return false;
    };
    for (ann, extended) in &state.open_annotations {
        if *extended {
            let pat = format!("</?{ann}.*>");
            if let Ok(re) = regex::Regex::new(&pat)
                && re.is_match(&src)
            {
                return true;
            }
        }
    }
    false
}

/// `WTSUtils::origSrcValidInEditedContext` — in selser mode, is an unedited
/// node's wikitext source reusable as-is in the surrounding edited context?
pub fn orig_src_valid_in_edited_context(
    state: &crate::html::serializer_state::SerializerState,
    tree: &crate::html::dom_tree::DomTree,
    id: crate::html::dom_tree::NodeId,
) -> bool {
    let node = tree.node(id);
    let name = node_name(node);

    if is_redirect_link(node) {
        return !tree.prev_sibling(id).is_some()
            && crate::html::dom_utils::at_the_top(tree, tree.parent(id).unwrap_or(id));
    }

    if dsr_contains_open_extended_range_annotation_tag(state, node) {
        return false;
    }

    if name == "th" || name == "td" {
        // Cell wikitext depends on position (first cell is single char).
        let Some(prev_id) = tree.prev_sibling(id) else {
            return true;
        };
        let prev = tree.node(prev_id);
        if crate::html::diff_utils::DiffUtils::has_inserted_diff_mark(prev)
            || crate::html::diff_utils::DiffUtils::has_inserted_diff_mark(node)
        {
            return false;
        }
        if !crate::html::diff_utils::DiffUtils::is_diff_marker(prev, None)
            && !crate::html::diff_utils::DiffUtils::direct_children_changed(prev)
        {
            return true;
        }
        return node.dp.as_ref().and_then(|d| d.stx.as_deref()) != Some("row");
    }

    if matches!(node.kind, NodeKind::Element(_))
        && name == "tr"
        && node.dp.as_ref().is_none_or(|d| d.start_tag_src.is_none())
    {
        // First row of a table (no startTagSrc) is reusable only if it stays
        // the first row.
        return crate::html::dom_tree::previous_non_sep_sibling(tree, id).is_none();
    }

    if is_nested_list_or_list_item(tree, id) {
        if crate::html::dom_utils::is_list(node) {
            // Lists never get bullets; nested lists can't be reused unless
            // they have a previous sibling.
            if tree.prev_sibling(id).is_none() {
                return false;
            }
        } else {
            // Reusable nested list items always have multiple bullets.
            let dp = node.dp.as_ref();
            let open_width_ok = dp
                .and_then(|d| d.dsr.as_ref())
                .and_then(|d| d.open_width)
                .is_some_and(|w| w >= 2);
            if !open_width_ok {
                return false;
            }
        }

        // If a previous sibling was modified, we can't reuse the start dsr.
        let mut prev = tree.prev_sibling(id);
        while let Some(p) = prev {
            let pn = tree.node(p);
            if crate::html::diff_utils::DiffUtils::is_diff_marker(pn, None)
                || crate::html::diff_utils::DiffUtils::has_inserted_diff_mark(pn)
            {
                return false;
            }
            prev = tree.prev_sibling(p);
        }
        return true;
    }

    if is_moved_meta_tag(node) {
        return false;
    }

    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_shadow_info_falls_back_to_attr() {
        // No `a` shadow entry → plain round-trip, `modified` = isNewElt.
        let mut node = Node::element(ElementKind::Other("span".to_string()));
        node.set_attr("title", "current");
        // No dp → isNewElt true → modified.
        let si = get_shadow_info(&node, "title", Some("current"));
        assert_eq!(si.value, "current");
        assert!(si.modified);
        assert!(!si.fromsrc);
    }

    #[test]
    fn test_get_shadow_info_from_src() {
        let mut node = Node::element(ElementKind::Other("span".to_string()));
        node.set_attr("title", "normalized");
        let mut dp = crate::wikitext::tokens_v2::DataParsoid::default();
        dp.set_a("title", "normalized");
        dp.set_sa("title", "Original Title");
        node.dp = Some(dp);
        let si = get_attribute_shadow_info(&node, "title");
        assert_eq!(si.value, "Original Title");
        assert!(!si.modified);
        assert!(si.fromsrc);
    }

    #[test]
    fn test_get_shadow_info_modified() {
        let mut node = Node::element(ElementKind::Other("span".to_string()));
        node.set_attr("title", "changed");
        let mut dp = crate::wikitext::tokens_v2::DataParsoid::default();
        dp.set_a("title", "original");
        node.dp = Some(dp);
        let si = get_attribute_shadow_info(&node, "title");
        assert_eq!(si.value, "changed");
        assert!(si.modified);
        assert!(!si.fromsrc);
    }

    #[test]
    fn test_escape_nowiki_tags() {
        assert_eq!(
            escape_nowiki_tags("<nowiki>x</nowiki>"),
            "&lt;nowiki&gt;x&lt;/nowiki&gt;"
        );
        assert_eq!(escape_nowiki_tags("plain"), "plain");
        assert_eq!(escape_nowiki_tags("a <b> c"), "a <b> c"); // non-nowiki untouched
    }

    #[test]
    fn test_is_valid_sep() {
        assert!(is_valid_sep(" \n\t"));
        assert!(is_valid_sep(" <!-- c --> \n"));
        assert!(!is_valid_sep("x"));
        assert!(!is_valid_sep("<!-- unclosed"));
    }

    #[test]
    fn test_comment_wt() {
        assert_eq!(comment_wt("foo"), "<!--foo-->");
        assert_eq!(comment_wt("a --> b"), "<!--a --&gt; b-->");
    }

    #[test]
    fn test_element_tag() {
        assert_eq!(element_tag(&ElementKind::Paragraph), "p");
        assert_eq!(element_tag(&ElementKind::Heading(3)), "h3");
        assert_eq!(element_tag(&ElementKind::Bold), "b");
    }

    #[test]
    fn test_is_quote_elt() {
        assert!(is_quote_elt(&Node::element(ElementKind::Italic)));
        assert!(is_quote_elt(&Node::element(ElementKind::Bold)));
        assert!(!is_quote_elt(&Node::element(ElementKind::Paragraph)));
    }

    #[test]
    fn test_get_dsr_and_has_valid_tag_widths() {
        use crate::html::dsr::DomSourceRange as SerializerDsr;
        use crate::wikitext::tokens_v2::DomSourceRange;

        // No dp → None.
        let plain = Node::element(ElementKind::Paragraph);
        assert!(get_dsr(&plain).is_none());

        // dp with dsr → lifted to the serializer DSR.
        let mut node = Node::element(ElementKind::Paragraph);
        let dp = crate::wikitext::tokens_v2::DataParsoid {
            dsr: Some(DomSourceRange {
                start: Some(10),
                end: Some(30),
                open_width: Some(2),
                close_width: Some(3),
            }),
            ..Default::default()
        };
        node.dp = Some(dp);

        let dsr = get_dsr(&node).unwrap();
        assert_eq!(dsr.start, Some(10));
        assert_eq!(dsr.end, Some(30));
        assert_eq!(dsr.open_width, Some(2));
        assert_eq!(dsr.close_width, Some(3));
        // html2wt-only fields default.
        assert_eq!(dsr.leading_ws, 0);
        assert_eq!(dsr.trailing_ws, 0);
        assert!(dsr.source.is_none());
        assert!(has_valid_tag_widths(Some(&dsr)));

        // Null widths → not valid.
        let wide = SerializerDsr::new(Some(10), Some(30), None, Some(3), 0, 0);
        assert!(!has_valid_tag_widths(Some(&wide)));
        assert!(!has_valid_tag_widths(None));
    }

    fn link_node(rel: &str) -> Node {
        let mut node = Node::element(ElementKind::InterlanguageLink);
        node.set_attr("rel", rel);
        node
    }

    #[test]
    fn test_is_redirect_link() {
        assert!(is_redirect_link(&link_node("mw:PageProp/redirect")));
        assert!(is_redirect_link(&link_node(
            "mw:PageProp/redirect mw:something"
        )));
        assert!(!is_redirect_link(&link_node("mw:PageProp/redirectto"))); // word boundary
        assert!(!is_redirect_link(&link_node("mw:PageProp/Category")));
    }

    #[test]
    fn test_emits_sol_transparent_single_line_wt() {
        assert!(emits_sol_transparent_single_line_wt(&Node::text("  \t")));
        assert!(!emits_sol_transparent_single_line_wt(&Node::text(" x")));
        assert!(!emits_sol_transparent_single_line_wt(&Node::text("")));
        assert!(emits_sol_transparent_single_line_wt(&Node::comment("c")));
        assert!(emits_sol_transparent_single_line_wt(&link_node(
            "mw:PageProp/Category"
        )));
        assert!(!emits_sol_transparent_single_line_wt(&Node::element(
            ElementKind::Paragraph
        )));
    }

    #[test]
    fn test_orig_src_valid_in_edited_context_plain() {
        use crate::html::dom_tree::DomTree;
        use crate::html::serializer_state::SerializerState;

        // A plain, unmarked paragraph reuses source.
        let mut root = Node::document();
        root.push_child(Node::element(ElementKind::Paragraph));
        let tree = DomTree::new(root);
        let st = SerializerState::new();
        let p = tree.first_child(tree.root()).unwrap();
        assert!(orig_src_valid_in_edited_context(&st, &tree, p));
    }

    #[test]
    fn test_orig_src_valid_moved_meta_false() {
        use crate::html::dom_tree::DomTree;
        use crate::html::serializer_state::SerializerState;

        // A moved annotation meta cannot reuse source.
        let mut root = Node::document();
        let mut meta = Node::element(ElementKind::Annotation);
        meta.data_parsoid = Some(r#"{"wasMoved":true}"#.to_string());
        root.push_child(meta);
        let tree = DomTree::new(root);
        let st = SerializerState::new();
        let m = tree.first_child(tree.root()).unwrap();
        assert!(!orig_src_valid_in_edited_context(&st, &tree, m));
    }

    #[test]
    fn test_next_to_deleted_block_node_in_wt() {
        use crate::html::dom_tree::DomTree;

        // No diff markers → not next to a deleted block node.
        let mut root = Node::document();
        root.push_child(Node::element(ElementKind::Paragraph));
        root.push_child(Node::element(ElementKind::Paragraph));
        let tree = DomTree::new(root);
        let p1 = tree.first_child(tree.root()).unwrap();
        assert!(!next_to_deleted_block_node_in_wt(&tree, p1, true));
        assert!(!next_to_deleted_block_node_in_wt(&tree, p1, false));
    }
}
