//! The auto-generated table-of-contents placeholder.
//!
//! rustoid targets the HTML a wiki *serves*, which is Parsoid's output after
//! core's `ParserOutput` post-processing. For a main-namespace page with enough
//! headings, no `__NOTOC__` and no explicit TOC, core appends
//! `<meta property="mw:PageProp/toc" data-mw='{"autoGenerated":true}'>` to the
//! end of section 0 (`Parser::internalParseHalfParsed`); the client renders the
//! table of contents there. Parsoid standalone never emits it, which is why the
//! fixture suite cannot see it either.
//!
//! The pass needs a section 0 to append to, so it is a no-op wherever section
//! wrapping did not run — the fragment and fixture paths.

use crate::dom::node::{ElementKind, Node, NodeKind};

/// Core shows a TOC from four headings up: "if there are fewer than 4 headlines
/// in the article, do not show TOC unless it's been explicitly enabled."
const MIN_HEADINGS: usize = 4;

/// Append the placeholder to section 0 when the page qualifies.
///
/// An explicit TOC — `__TOC__`, or a template that emits one as `{{TOC limit}}`
/// does — already puts a `mw:PageProp/toc` meta in the tree, and `__NOTOC__`
/// puts a `mw:PageProp/notoc`; either suppresses the auto one, exactly as core's
/// `mForceTocPosition`/`mShowToc` do.
pub fn insert(ast: &mut Node, is_main_namespace: bool) {
    if !is_main_namespace {
        return;
    }
    let mut headings = 0usize;
    let mut has_toc_switch = false;
    scan(ast, &mut headings, &mut has_toc_switch);
    if has_toc_switch || headings < MIN_HEADINGS {
        return;
    }
    let Some(section) = lead_section(ast) else {
        return;
    };
    let mut meta = Node::element(ElementKind::Other("meta".to_string()));
    meta.set_attr("property", "mw:PageProp/toc");
    // `data-mw` is what gives the meta a generated node id, matching the served
    // `<meta … data-mw='{"autoGenerated":true}' id="mw…"/>`.
    meta.data_mw = Some(r#"{"autoGenerated":true}"#.to_string());
    section.push_child(meta);
}

/// Count headings and note any `mw:PageProp/toc`/`notoc` meta.
fn scan(node: &Node, headings: &mut usize, has_toc_switch: &mut bool) {
    if node.kind.is_element() {
        if matches!(node.kind, NodeKind::Element(ElementKind::Heading(_)))
            || matches!(&node.kind, NodeKind::Element(ElementKind::Other(tag))
                if matches!(tag.as_str(), "h1" | "h2" | "h3" | "h4" | "h5" | "h6"))
        {
            *headings += 1;
        }
        if matches!(
            node.get_attr("property"),
            Some("mw:PageProp/toc") | Some("mw:PageProp/notoc")
        ) {
            *has_toc_switch = true;
        }
    }
    for child in &node.children {
        scan(child, headings, has_toc_switch);
    }
}

/// The lead `<section data-mw-section-id="0">` inside the tree builder's
/// `<html>` wrapper.
fn lead_section(ast: &mut Node) -> Option<&mut Node> {
    let html = ast
        .children
        .iter_mut()
        .find(|c| matches!(&c.kind, NodeKind::Element(ElementKind::Other(tag)) if tag == "html"))?;
    html.children.iter_mut().find(|c| {
        matches!(c.kind, NodeKind::Element(ElementKind::Section))
            && c.get_attr("data-mw-section-id") == Some("0")
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dom::node::Node;

    fn heading(level: u8) -> Node {
        Node::element(ElementKind::Heading(level))
    }

    fn page(children: Vec<Node>) -> Node {
        let mut html = Node::element(ElementKind::Other("html".to_string()));
        let mut section = Node::element(ElementKind::Section);
        section.set_attr("data-mw-section-id", "0");
        for c in children {
            section.push_child(c);
        }
        html.push_child(section);
        let mut root = Node::document();
        root.push_child(html);
        root
    }

    fn toc_meta_count(node: &Node) -> usize {
        let mut n = usize::from(node.get_attr("property") == Some("mw:PageProp/toc"));
        for c in &node.children {
            n += toc_meta_count(c);
        }
        n
    }

    #[test]
    fn four_headings_get_a_placeholder() {
        let mut ast = page(vec![heading(2), heading(2), heading(2), heading(2)]);
        insert(&mut ast, true);
        assert_eq!(toc_meta_count(&ast), 1);
    }

    #[test]
    fn three_headings_do_not() {
        let mut ast = page(vec![heading(2), heading(2), heading(2)]);
        insert(&mut ast, true);
        assert_eq!(toc_meta_count(&ast), 0);
    }

    #[test]
    fn not_main_namespace_does_not() {
        let mut ast = page(vec![heading(2), heading(2), heading(2), heading(2)]);
        insert(&mut ast, false);
        assert_eq!(toc_meta_count(&ast), 0);
    }

    #[test]
    fn an_explicit_toc_suppresses_the_auto_one() {
        let mut explicit = Node::element(ElementKind::Other("meta".to_string()));
        explicit.set_attr("property", "mw:PageProp/toc");
        let mut ast = page(vec![
            heading(2),
            heading(2),
            heading(2),
            heading(2),
            explicit,
        ]);
        insert(&mut ast, true);
        assert_eq!(toc_meta_count(&ast), 1, "only the authored meta remains");
    }

    #[test]
    fn notoc_suppresses_the_auto_one() {
        let mut notoc = Node::element(ElementKind::Other("meta".to_string()));
        notoc.set_attr("property", "mw:PageProp/notoc");
        let mut ast = page(vec![heading(2), heading(2), heading(2), heading(2), notoc]);
        insert(&mut ast, true);
        assert_eq!(toc_meta_count(&ast), 0);
    }
}
